name: Auto PR from issue
on:
  issues:
    types: [labeled]

jobs:
  create_auto_pr:
    if: github.event.label.name == 'autopr'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install openai pyyaml

      - name: Generate patch using OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python .github/scripts/issue_to_pr.py "${{ github.event.issue.number }}" "${{ github.repository }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "auto/issue-${{ github.event.issue.number }}"
          title: "Auto PR for #${{ github.event.issue.number }}"
          commit-message: "Auto changes for issue #${{ github.event.issue.number }}"
          body: "PR automatically generated by OpenAI for issue #${{ github.event.issue.number }}"
