"""
==========================================================================
script_generator.py
==========================================================================
A translator to translate yaml-formatted IR generated by compiler to the
packets used in VectorCGRA

Author : Bohan Cui
  Date : Feb 25, 2026
"""

### Usage:
# 1. create factory instance with the types
# (for the spec of the types, please refer to e.g. cgra/test/CgraRTL_fir_test.py)
# ```
# script_factory = ScriptFactory(
#     path = the_input_yaml,
#     CtrlType = your_CtrlType,
#     IntraCgraPktType = your_IntraCgraPktType,
#     CgraPayloadType = your_CgraPayloadType,
#     TileInType = your_TileInType,
#     FuOutType = your_FuOutType,
#     CMD_CONFIG_input = your_CMD_CONFIG_input,
#     FuInType = your_FuInType,
#     ii = your_ii,
#     loop_times = your_loop_times,
#     CMD_CONST_input = your_CMD_CONST_input,
#     CMD_CONFIG_COUNT_PER_ITER_input = your_CMD_CONFIG_COUNT_PER_ITER_input,
#     CMD_CONFIG_TOTAL_CTRL_COUNT_input = your_CMD_CONFIG_TOTAL_CTRL_COUNT_input,
#     CMD_CONFIG_PROLOGUE_FU_input = your_CMD_CONFIG_PROLOGUE_FU_input,
#     CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input = your_CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input,
#     CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input = your_CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input,
#     CMD_LAUNCH_input = your_CMD_LAUNCH_input,
#     DataType = your_DataType,
#     B1Type = your_B1Type,
#     B2Type = your_B2Type,
#     RegIdxType = your_RegIdxType,
#     CtrlAddrType = your_CtrlAddrType,
#     DataAddrType = your_DataAddrType,
# )
# ```
# 2. make the packets
# pkts = script_factory.makeVectorCGRAPkts()

import sys
import os
import yaml

# Set to True for verbose debug output during packet generation
VERBOSE_PKT_GEN = os.environ.get('VERBOSE_PKT_GEN', '0') == '1'

# Add project root to path to allow imports from lib
# Get the absolute path of this file
_script_dir = os.path.dirname(os.path.abspath(__file__))
# Get the project root (parent of validation directory)
project_root = os.path.dirname(_script_dir)
# Normalize the path to handle any symlinks or relative path issues
project_root = os.path.normpath(os.path.abspath(project_root))

if project_root not in sys.path:
    sys.path.insert(0, project_root)

from lib.opt_type import *

# Global configuration for register cluster size (number of registers per cluster).
# This can be overridden by ScriptFactory initialization.
REG_CLUSTER_SIZE = 8

yaml_to_VectorCGRA_map = {
    "CONSTANT": OPT_CONST, # ?
    "ADD": OPT_ADD,
    "MUL": OPT_MUL,
    "SUB": OPT_SUB,
    "DIV": OPT_DIV,
    "REM": OPT_REM,
    "FADD": OPT_FADD,
    "FSUB": OPT_FSUB,
    "FMUL": OPT_FMUL,
    "FDIV": None, # ?
    "OR": OPT_OR,
    "AND": OPT_AND,
    "NOT": OPT_NOT,
    "ICMP_EQ": OPT_EQ, # ?
    "ICMP_SGE": OPT_GTE,
    "ICMP_ULT": OPT_LT,
    "ICMP_SGT": OPT_GT,
    "ICMP_SLT": OPT_LT,
    "FCMP": None, # ?
    "SEL": OPT_SEL,
    "CAST": None, # ?
    "SEXT": OPT_PAS, # no sext, just a fake one.
    "ZEXT": OPT_PAS, # no zext, just a fake one (pass-through).
    "CAST_TRUNC": OPT_PAS, # truncation treated as pass-through.
    "SHL": OPT_LLS,
    "VFMUL": None, # ?
    "FADD_FADD": None, #?
    "FMUL_FADD": None, #?
    "DATA_MOV": None, #?
    "CTRL_MOV": None, #?
    "RESERVE": None, #?
    "GRANT_PREDICATE": OPT_GRT_PRED,
    "GRANT_ALWAYS": None, #?
    "GRANT_ONCE": OPT_GRT_ONCE, #?
    "PHI": OPT_PHI,
    "LOOP_CONTROL": None, #?
    "PHI_CONST": OPT_PHI_CONST,
    "PHI_START": OPT_PHI_START,

    "GEP": OPT_ADD, # By now, we just support 2 op GEP and it is equivalent to ADD (base + index)
    "GEP_2D": OPT_GEP_2D, # special GEP for 2D array access, with 3 operands (base, idx1, idx2) and idx1/idx2 are multiplied with different stride.

    "RETURN": OPT_RET,
    "RETURN_VALUE": OPT_RET,
    "RETURN_VOID": OPT_RET_VOID,
    "LDD": OPT_LD,
    "LOAD": OPT_LD,
    "STORE": OPT_STR,

    "NE": OPT_NE,
    "MUL_ADD": OPT_MUL_ADD,
    "DATA_MOV": OPT_PAS

}

yaml_to_VectorCGRA_map_const = {
    "CONSTANT": OPT_CONST,
    "NE": OPT_NE_CONST,
    "ADD": OPT_ADD_CONST,
    "MUL_ADD": OPT_MUL_CONST_ADD,
    "MUL": OPT_MUL_CONST,
    "SUB": OPT_SUB_CONST,
    "DIV": OPT_DIV_CONST,
    "REM": OPT_REM_CONST,
    "GEP": OPT_ADD_CONST, # For 2-op GEP with const base: base(const) + index(in0)
    "GEP_2D": OPT_GEP_2D_CONST,
    # Note: 3-op GEP with const base uses OPT_GEP_2D_CONST (handled dynamically)
    "ICMP_EQ": OPT_EQ_CONST,
    "ICMP_SGE": OPT_GTE_CONST,
    "ICMP_ULT": OPT_LT_CONST,
    "ICMP_SGT": OPT_GT_CONST,
    "ICMP_SLT": OPT_LT_CONST,
    "AND": OPT_AND_CONST,
    "OR": OPT_OR_CONST,
    "CONSTANT": OPT_CONST,
    "SHL": OPT_LLS_CONST,

    "GRANT_ONCE": OPT_GRT_ONCE_CONST,
    "STORE": OPT_STR_CONST,  # default; overridden for STORE with const data
}



def _type(Operand):
    impl = Operand['operand']
    if impl[0] == "$":
        return 'REG'
    elif impl.upper() in ['NORTH', 'SOUTH', 'WEST', 'EAST', 'SOUTHEAST', 'SOUTHWEST', 'NORTHWEST', 'NORTHEAST']:
        return 'PORT'
    else:
        return 'IMM'

def direction_to_idx(direction):
    if direction == 'NORTH':
        return 0
    elif direction == 'SOUTH':
        return 1
    elif direction == 'WEST':
        return 2
    elif direction == 'EAST':
        return 3
    else:
        raise ValueError("Invalid direction: ", direction)

def _is_take_up_fu_operation(operation):
    if operation['opcode'] == 'MOV' or operation['opcode'] == 'DATA_MOV' or operation['opcode'] == 'CTRL_MOV':
        if len(operation['src_operands']) != 1:
            raise ValueError("MOV operation must have exactly one source operand")
        elif _type(operation['src_operands'][0]) == 'PORT':
            return False # By now, only Port -> Port and Port -> Reg are not take up fu operations
        elif _type(operation['src_operands'][0]) == 'REG':
            return False
        else:
            # REG -> PORT only: can be handled by FU output crossbar routing
            # without occupying the FU, so treat as not-take-up-fu.
            dst_operands = operation.get('dst_operands', [])
            if dst_operands and all(_type(d) == 'PORT' for d in dst_operands):
                return False
            return True
    else:
        return True

def _take_up_fu_operation_idx_of(operations: list):
    # check if there is only < 1 take up fu operation, if 1, return the idx, if > 1, raise error, if 0, return -1
    take_up_fu_operation_idx = -1
    for idx, operation in enumerate(operations):
        if _is_take_up_fu_operation(operation):
            if take_up_fu_operation_idx != -1:
                raise ValueError("Only one take up fu operation is allowed, panic in instruction ", operations)
            take_up_fu_operation_idx = idx
    return take_up_fu_operation_idx

def _reg_cluster_no_of(operand): # start from 1
    impl = operand['operand']
    if impl[0] == "$":
        return int(impl[1:]) // REG_CLUSTER_SIZE + 1
    else:
        raise ValueError("Operand is not a register")

def _reg_cluster_intra_index_of(operand):
    impl = operand['operand']
    if impl[0] == "$":
        return int(impl[1:]) % REG_CLUSTER_SIZE
    else:
        raise ValueError("Operand is not a register")

def print_instruction(instruction):
    if VERBOSE_PKT_GEN: print(f"Instruction: {[operation['opcode'] for operation in instruction['operations']]}")

FROM_NOWHERE = 0
FROM_PORT = 1
FROM_FU = 2
FROM_CONSTANT_QUEUE = 3 # not used by now

OPR_FROM_PORT = 0        # read_reg_towards = 0 = READ_TOWARDS_NOTHING
OPR_FROM_REGISTER = 1    # read_reg_towards = 1 = READ_TOWARDS_FU
OPR_TOWARDS_ROUTING = 2  # read_reg_towards = 2 = READ_TOWARDS_ROUTING_XBAR
OPR_TOWARDS_BOTH = 3     # read_reg_towards = 3 = READ_TOWARDS_BOTH

class InstructionSignals:
    # to make signal of single instruction
    def __init__(self,
                 # input
                 id_,
                 operations,
                 opcode_in_EIR,
                 ctrl_addr,
                 # types
                 IntraCgraPktType,
                 CgraPayloadType,
                 TileInType,
                 FuOutType,
                 CMD_CONFIG_input,
                 CtrlType,
                 FuInType,
                 B1Type,
                 B2Type,
                 RegIdxType,
                 CtrlAddrType,
                 accumulate_add_to_src_reg=False):
        # types
        self.IntraCgraPktType = IntraCgraPktType
        self.CgraPayloadType = CgraPayloadType
        self.TileInType = TileInType
        self.FuOutType = FuOutType
        self.CMD_CONFIG_ = CMD_CONFIG_input
        self.CtrlType = CtrlType
        self.FuInType = FuInType
        self.B1Type = B1Type
        self.B2Type = B2Type
        self.RegIdxType = RegIdxType
        self.CtrlAddrType = CtrlAddrType
        self.accumulate_add_to_src_reg = accumulate_add_to_src_reg

        # inputs
        self.id_ = id_
        self.operations = operations
        self.OpCode = opcode_in_EIR
        self.ctrl_addr = ctrl_addr

        # States
        self.TileInParams = [-1, -1, -1, -1, -1, -1, -1, -1]
        self.FuOutParams = [-1, -1, -1, -1, -1, -1, -1, -1]
        self.read_reg_towards_fu = [-1, -1, -1, -1]
        self.read_reg_towards_xbar = [-1, -1, -1, -1]
        self.operand_from = [-1, -1, -1, -1]
        self.read_towards_reg_idx = [-1, -1, -1, -1]
        self.write_to_reg = [-1, -1, -1, -1]
        self.write_to_reg_idx = [-1, -1, -1, -1]
        self.shuffle_fu_operand_input_index = [-1, -1, -1, -1]


    def buildCtrlPkt(self) -> list: # return the const needed to put into the const queue
        # you must call buildCtrlPkt before makeCtrlPkt, and for a Tile's signal, you must call buildCtrlPkt in order.
        try:

            # 1. Find take up fu operation
            take_up_fu_operation_idx = _take_up_fu_operation_idx_of(self.operations)

            if take_up_fu_operation_idx == -1:
                if VERBOSE_PKT_GEN: print("No take up fu operation found, just take the first.")
                take_up_fu_operation_idx = 0
                take_up_fu_operation = "NAH"
                self.OpCode = OPT_NAH
            else:
                if VERBOSE_PKT_GEN: print("Take_up_fu_operation: ", self.operations[take_up_fu_operation_idx])
                take_up_fu_operation = self.operations[take_up_fu_operation_idx]
                # only take up fu can be const
                has_const = False
                # if has src_operands, check if has const
                try:
                    src_operands = take_up_fu_operation['src_operands']
                except Exception as e:
                    src_operands = []
                for src_operand in src_operands:
                    if _type(src_operand) == 'IMM':
                        has_const = True
                        break

                #if take_up_fu_operation['opcode'] == 'PHI_CONST' or take_up_fu_operation['opcode'] == 'CONSTANT':
                    #has_const = False # PHI_CONST and CONSTANT are special.

                if has_const:
                    self.OpCode = yaml_to_VectorCGRA_map_const[self.operations[take_up_fu_operation_idx]['opcode']]
                    # Special handling for STORE with const:
                    # YAML STORE format is [data, addr]. After swap → [addr, data].
                    # If the IMM is the DATA (position 0 in YAML), use OPT_STR_DATA_CONST.
                    # If the IMM is the ADDR (position 1 in YAML), use OPT_STR_CONST.
                    if take_up_fu_operation['opcode'] == 'STORE':
                        if len(src_operands) >= 2 and _type(src_operands[0]) == 'IMM':
                            # Data is const (position 0 in YAML → position 1 after swap)
                            self.OpCode = OPT_STR_DATA_CONST
                        else:
                            # Address is const (position 1 in YAML → position 0 after swap)
                            self.OpCode = OPT_STR_CONST
                    # Special handling for 3-operand GEP with const base (2D array access):
                    # If GEP has 3 src_operands and one is an IMM (const base),
                    # use OPT_GEP_2D_CONST instead of OPT_ADD_CONST.
                    if take_up_fu_operation['opcode'] == 'GEP':
                        non_imm_count = sum(1 for op in src_operands if _type(op) != 'IMM')
                        if non_imm_count >= 2:
                            self.OpCode = OPT_GEP_2D_CONST
                else:
                    self.OpCode = yaml_to_VectorCGRA_map[self.operations[take_up_fu_operation_idx]['opcode']]

            const_operands = []

            # Two-pass processing: First handle non-FU operations (to reserve
            # their fixed lanes/TileInParams), then handle FU operations (which
            # pick from remaining available lanes).
            ordered_operations = sorted(
                self.operations,
                key=lambda op: 0 if not _is_take_up_fu_operation(op) else 1)

            for operation in ordered_operations: # for each operation in the instruction

                if VERBOSE_PKT_GEN: print("\n Operation: ", operation)

                operation_opcode = operation['opcode']
                try:
                    src_operands = operation['src_operands'].copy()
                    if operation_opcode == 'STORE' and len(src_operands) >= 2:
                        # HW expects address in0 and data in1, but YAML gives [data, addr]
                        src_operands[0], src_operands[1] = src_operands[1], src_operands[0]
                except Exception as e:
                    src_operands = []
                try:
                    dst_operands = list(operation['dst_operands'])
                except Exception as e:
                    dst_operands = []

                # find all the const
                for index, src_operand in enumerate(src_operands):
                    if _type(src_operand) == 'IMM':
                        const_operands.append((src_operand, operation["time_step"]))
                        # delete it from the src_operands since it is implicit in vectorCGRA
                        del src_operands[index]

                if self.accumulate_add_to_src_reg and operation_opcode == 'ADD':
                    reg_src_operands = [
                        operand for operand in src_operands
                        if _type(operand) == 'REG'
                    ]
                    has_reg_dst = any(_type(operand) == 'REG'
                                      for operand in dst_operands)
                    if reg_src_operands and not has_reg_dst:
                        dst_operands.append(reg_src_operands[0])

                # for not_take_up_fu_operation
                if not _is_take_up_fu_operation(operation):

                    if len(src_operands) != 1:
                        raise ValueError(f"Not take up fu operation {operation} must have exactly one source operand.")

                    src_operand = src_operands[0]

                    # REG -> PORT: route via FU output crossbar (merge with
                    # the take-up-fu operation's output routing).
                    if _type(src_operand) == 'REG':
                        intra_index = _reg_cluster_intra_index_of(src_operand)
                        cluster_no = _reg_cluster_no_of(src_operand)

                        # check collision
                        if self.read_reg_towards_xbar[cluster_no - 1] != -1 and self.read_towards_reg_idx[cluster_no - 1] != intra_index:
                            # another register calls for sending to the FU
                            raise ValueError(f"Collision when reading from register in read_reg_towards_fu, when translate the operation {operation} to VectorCGRA")

                        if self.operand_from[cluster_no - 1] != -1 and self.operand_from[cluster_no - 1] == OPR_FROM_PORT:
                            raise ValueError(f"The register operand overwrite the port operand in lane {cluster_no -1}")
                        for index, dst_operand in enumerate(dst_operands):
                            if _type(dst_operand) == 'PORT':
                                if dst_operand['operand'] == 'NORTH':
                                    port_out_xbar_idx = 0
                                elif dst_operand['operand'] == 'SOUTH':
                                    port_out_xbar_idx = 1
                                elif dst_operand['operand'] == 'WEST':
                                    port_out_xbar_idx = 2
                                elif dst_operand['operand'] == 'EAST':
                                    port_out_xbar_idx = 3
                                if self.TileInParams[port_out_xbar_idx] != -1:
                                    # another source want to send to the direction
                                    raise ValueError(f"Collision in writing to port {dst_operand} in FuOutParams (REG->PORT), when translate the operation {operation} to VectorCGRA")
                                self.TileInParams[port_out_xbar_idx] = cluster_no + 4 # directly route from the register cluster to the port, no need to shuffle to FU first
                                self.read_reg_towards_xbar[cluster_no - 1] = 1
                                self.read_towards_reg_idx[cluster_no - 1] = intra_index
                                self.operand_from[cluster_no - 1] = OPR_FROM_REGISTER
                            else:
                                raise ValueError(f"REG->non-PORT dst {dst_operand} classified as not take-up-fu, when translate the operation {operation} to VectorCGRA")
                        continue

                    elif _type(src_operand) == 'PORT':
                        src_direction_idx = direction_to_idx(src_operand['operand'])

                        for index, dst_operand in enumerate(dst_operands):
                            if _type(dst_operand) == 'REG':
                                cluster_no = _reg_cluster_no_of(dst_operand)
                                intra_index = _reg_cluster_intra_index_of(dst_operand)
                                # set the TileInParams
                                if self.TileInParams[cluster_no + 4 - 1] != -1 and self.TileInParams[cluster_no + 4 - 1] != src_direction_idx + 1:
                                    raise ValueError(f"Collision when reading from port in TileInParams, when translate the operation {operation} to VectorCGRA")
                                self.TileInParams[cluster_no + 4 - 1] = src_direction_idx + 1

                                if self.write_to_reg_idx[cluster_no - 1] != -1 and self.write_to_reg_idx[cluster_no - 1] != intra_index:
                                    raise ValueError(f"Collision when writing to register in write_to_reg_idx, when translate the operation {operation} to VectorCGRA")
                                self.write_to_reg[cluster_no - 1] = FROM_PORT
                                self.write_to_reg_idx[cluster_no - 1] = intra_index
                            elif _type(dst_operand) == 'PORT':
                                if dst_operand['operand'] == 'NORTH':
                                    port_out_xbar_idx = 0
                                elif dst_operand['operand'] == 'SOUTH':
                                    port_out_xbar_idx = 1
                                elif dst_operand['operand'] == 'WEST':
                                    port_out_xbar_idx = 2
                                elif dst_operand['operand'] == 'EAST':
                                    port_out_xbar_idx = 3
                                if self.TileInParams[port_out_xbar_idx] != -1 and self.TileInParams[port_out_xbar_idx] != src_direction_idx + 1:
                                    raise ValueError(f"Collision in writing to port {dst_operand} in FuOutParams, when translate the operation {operation} to VectorCGRA")
                                self.TileInParams[port_out_xbar_idx] = src_direction_idx + 1 # 1,2,3,4 for N,S,W,E
                            else:
                                raise ValueError(f"Unsupported type of dst operand {dst_operand}, when translate the operation {operation} to VectorCGRA")
                        continue


                # reorder the src operands since register has high priority (cause reg can't be shuffled but port can be shuffled)
                # TODO: not complete, actually should also take dst into account
                reordered_src_operands = {}
                for index, src_operand in enumerate(src_operands):
                    if _type(src_operand) == 'REG':
                        reordered_src_operands[index] = src_operand
                for index, src_operand in enumerate(src_operands):
                    if not _type(src_operand) == 'REG':
                        reordered_src_operands[index] = src_operand

                for index, src_operand in reordered_src_operands.items():
                    if _type(src_operand) == 'REG':
                        if VERBOSE_PKT_GEN: print(f">>> index {index} is REG")
                        cluster_no = _reg_cluster_no_of(src_operand)
                        intra_index = _reg_cluster_intra_index_of(src_operand)
                        # Check if cluster_no is within valid range (1 to num_fu_inports)
                        if cluster_no < 1 or cluster_no > len(self.read_towards_reg_idx):
                            raise ValueError(f"Register cluster number {cluster_no} is out of range. Valid range is 1 to {len(self.read_towards_reg_idx)} for register {src_operand['operand']} in operation {operation}")
                        # Check if intra_index is within valid range (0 to REG_CLUSTER_SIZE-1)
                        if intra_index < 0 or intra_index >= REG_CLUSTER_SIZE:
                            raise ValueError(f"Register intra index {intra_index} is out of range. Valid range is 0 to {REG_CLUSTER_SIZE-1} for register {src_operand['operand']} in operation {operation}")
                        if self.read_reg_towards_fu[cluster_no - 1] != -1 and self.read_towards_reg_idx[cluster_no - 1] != intra_index:
                            raise ValueError(f"Collision when reading from register in read_from_reg_idx, when translate the operation {operation} to VectorCGRA")
                        if self.operand_from[cluster_no - 1] != -1 and self.operand_from[cluster_no - 1] != OPR_FROM_REGISTER:
                            raise ValueError(f"Register operand overwrite the port operand in lane {cluster_no -1}, when translate the operation {operation} to VectorCGRA")
                        self.operand_from[cluster_no - 1] = OPR_FROM_REGISTER
                        self.read_towards_reg_idx[cluster_no - 1] = intra_index
                        self.read_reg_towards_fu[cluster_no - 1] = 1
                        if self.shuffle_fu_operand_input_index[index] != -1:
                            raise ValueError(f"Collision when reading from register in shuffle_fu_operand_input_index, when translate the operation {operation} to VectorCGRA")
                        self.shuffle_fu_operand_input_index[index] = cluster_no # shuffle the data to the correct inport of the FU from the register
                    if _type(src_operand) == 'PORT':
                        if src_operand['operand'] == 'NORTH':
                            port_in_xbar_idx = 1
                        elif src_operand['operand'] == 'SOUTH':
                            port_in_xbar_idx = 2
                        elif src_operand['operand'] == 'WEST':
                            port_in_xbar_idx = 3
                        elif src_operand['operand'] == 'EAST':
                            port_in_xbar_idx = 4

                        # find an available lane
                        lane = -1
                        for i in range(4):
                            ok = self.operand_from[i] == -1 and self.TileInParams[i + 4] == -1 # The lane is completely empty
                            ok = ok or (self.operand_from[i] == OPR_FROM_PORT and self.TileInParams[i + 4] == port_in_xbar_idx) # The lane is already used by the same port, can be reused
                            if ok:
                                lane = i
                                break
                        if lane == -1:
                            raise ValueError(f"No available lane found when reading from port {src_operand} in TileInParams, when translate the operation {operation} to VectorCGRA")
                        else:
                            if VERBOSE_PKT_GEN: print(f"Lane {lane} available for port source {src_operand}")
                        self.TileInParams[lane + 4] = port_in_xbar_idx
                        self.operand_from[lane] = OPR_FROM_PORT
                        # shuffle to the given fu input index
                        if self.shuffle_fu_operand_input_index[index] != -1:
                            raise ValueError(f"Collision when reading from port in shuffle_fu_operand_input_index {self.shuffle_fu_operand_input_index} (want to set opr {index} to {lane}), when translate the operation {operation} to VectorCGRA")
                        self.shuffle_fu_operand_input_index[index] = lane + 1

                    if _type(src_operand) == 'IMM':
                        raise NotImplementedError("IMM src should have been removed here")

                for index, dst_operand in enumerate(dst_operands):
                    if _type(dst_operand) == 'REG':
                        cluster_no = _reg_cluster_no_of(dst_operand)
                        intra_index = _reg_cluster_intra_index_of(dst_operand)
                        # Check if cluster_no is within valid range (1 to num_fu_inports)
                        if cluster_no < 1 or cluster_no > len(self.write_to_reg_idx):
                            raise ValueError(f"Register cluster number {cluster_no} is out of range. Valid range is 1 to {len(self.write_to_reg_idx)} for register {dst_operand['operand']} in operation {operation}")
                        # Check if intra_index is within valid range (0 to REG_CLUSTER_SIZE-1)
                        if intra_index < 0 or intra_index >= REG_CLUSTER_SIZE:
                            raise ValueError(f"Register intra index {intra_index} is out of range. Valid range is 0 to {REG_CLUSTER_SIZE-1} for register {dst_operand['operand']} in operation {operation}")
                        if self.write_to_reg_idx[cluster_no - 1] != -1 and self.write_to_reg_idx[cluster_no - 1] != intra_index:
                            raise ValueError(f"Collision when writing to register in write_to_reg_idx, when translate the operation {operation} to VectorCGRA")
                        self.write_to_reg[cluster_no - 1] = FROM_FU
                        self.write_to_reg_idx[cluster_no - 1] = intra_index
                        if self.FuOutParams[cluster_no + 3] != -1:
                            raise ValueError(f"Collision in writing result to register, when translate the operation {operation} to VectorCGRA")
                        self.FuOutParams[cluster_no + 3] = 1
                    elif _type(dst_operand) == 'PORT':
                        if dst_operand['operand'] == 'NORTH':
                            port_out_xbar_idx = 0
                        elif dst_operand['operand'] == 'SOUTH':
                            port_out_xbar_idx = 1
                        elif dst_operand['operand'] == 'WEST':
                            port_out_xbar_idx = 2
                        elif dst_operand['operand'] == 'EAST':
                            port_out_xbar_idx = 3
                        if self.FuOutParams[port_out_xbar_idx] != -1:
                            raise ValueError(f"Collision in writing to port {dst_operand} in FuOutParams, when translate the operation {operation} to VectorCGRA")
                        if VERBOSE_PKT_GEN: print(f">>> FuOutParams[{port_out_xbar_idx}] = {index + 1}")
                        self.FuOutParams[port_out_xbar_idx] = 1 # we do not support multiple results
                    else:
                        raise ValueError(f"Unsupported type of dst operand {dst_operand}, when translate the operation {operation} to VectorCGRA")

        except Exception as e:
            print(f"Error in making ctrl pkt: {e}")
            raise e
            return None
        return const_operands

    def makeCtrlPkt(self):
        # make fu_in_code
        for idx, fu_in_code in enumerate(self.shuffle_fu_operand_input_index):
            if fu_in_code == -1:
                self.shuffle_fu_operand_input_index[idx] = idx + 1
        fu_in_code_made = [self.FuInType(x) for x in self.shuffle_fu_operand_input_index] # is it correct?

        # make TileIn
        for idx, tile_in_param in enumerate(self.TileInParams):
            if tile_in_param == -1:
                self.TileInParams[idx] = 0
        TileIn_made = [self.TileInType(x) for x in self.TileInParams]
        for idx, fu_out_param in enumerate(self.FuOutParams):
            if fu_out_param == -1:
                self.FuOutParams[idx] = 0
        FuOut_made = [self.FuOutType(x) for x in self.FuOutParams]

        # made write reg from code
        for idx, write_to_reg in enumerate(self.write_to_reg):
            if write_to_reg == -1:
                self.write_to_reg[idx] = FROM_NOWHERE
        write_reg_from_made = [self.B2Type(x) for x in self.write_to_reg]

        for idx, write_to_reg_idx in enumerate(self.write_to_reg_idx):
            if write_to_reg_idx == -1:
                self.write_to_reg_idx[idx] = 0
        write_reg_idx_made = [self.RegIdxType(x) for x in self.write_to_reg_idx]

        # make read reg from code
        read_towards = [-1, -1, -1, -1]
        for idx in range(4):
             if self.read_reg_towards_fu[idx] == 1 and self.read_reg_towards_xbar[idx] == 1:
                read_towards[idx] = 3 # both
             elif self.read_reg_towards_fu[idx] == 1:
                read_towards[idx] = 1 # to fu
             elif self.read_reg_towards_xbar[idx] == 1:
                read_towards[idx] = 2 # to xbar
             else:
                read_towards[idx] = 0 # to nowhere

        # read_reg_towards uses 2-bit type (RegFromType): 0=nothing, 1=FU, 2=routing_xbar, 3=both
        read_reg_towards_made = [self.B2Type(x) for x in read_towards]

        for idx, read_towards_reg_idx in enumerate(self.read_towards_reg_idx):
            if read_towards_reg_idx == -1:
                self.read_towards_reg_idx[idx] = 0
        read_reg_idx_made = [self.RegIdxType(x) for x in self.read_towards_reg_idx]

        # make FuOut
        # CtrlType requires: operation, fu_in, routing_xbar_outport, fu_xbar_outport,
        #                    vector_factor_power, is_last_ctrl, write_reg_from, write_reg_idx,
        #                    read_reg_towards, read_reg_idx
        # Use keyword arguments for optional fields to avoid parameter order issues
        pkt = self.IntraCgraPktType(0, self.id_,
                                    payload = self.CgraPayloadType(self.CMD_CONFIG_,
                                                                    ctrl_addr = self.CtrlAddrType(self.ctrl_addr),
                                                                    ctrl = self.CtrlType(self.OpCode,
                                                                                        fu_in_code_made,
                                                                                        TileIn_made,
                                                                                        FuOut_made,
                                                                                        write_reg_from = write_reg_from_made,
                                                                                        write_reg_idx = write_reg_idx_made,
                                                                                        read_reg_towards = read_reg_towards_made,
                                                                                        read_reg_idx = read_reg_idx_made,
                                                                                        )))
        return pkt

class TileSignals:
    def __init__(self,
                CtrlType,
                IntraCgraPktType,
                CgraPayloadType,
                TileInType,
                FuOutType,
                CMD_CONFIG_input,
                FuInType,
                id_,
                loop_times,
                ii,
                instructions,
                CMD_CONST_input,
                CMD_CONFIG_COUNT_PER_ITER_input,
                CMD_CONFIG_TOTAL_CTRL_COUNT_input,
                CMD_CONFIG_PROLOGUE_FU_input,
                CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input,
                CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input,
                CMD_LAUNCH_input,
                DataType,
                B1Type,
                B2Type,
                RegIdxType,
                CtrlAddrType,
                DataAddrType,
                arg_map=None,
                gep_stride=None,
                use_time_step_ctrl_addr=False,
                accumulate_add_to_src_reg=False):
        self.CtrlType = CtrlType
        self.IntraCgraPktType = IntraCgraPktType
        self.CgraPayloadType = CgraPayloadType
        self.TileInType = TileInType
        self.FuOutType = FuOutType
        self.CMD_CONFIG_ = CMD_CONFIG_input
        self.FuInType = FuInType
        self.id_ = id_
        self.instructions = instructions
        self.loop_times = loop_times
        self.ii = ii
        self.B1Type = B1Type
        self.B2Type = B2Type
        self.RegIdxType = RegIdxType
        self.DataType = DataType
        self.CtrlAddrType = CtrlAddrType
        self.DataAddrType = DataAddrType
        self.arg_map = arg_map if arg_map is not None else {}
        self.gep_stride = gep_stride
        self.use_time_step_ctrl_addr = use_time_step_ctrl_addr
        self.accumulate_add_to_src_reg = accumulate_add_to_src_reg
        # constants
        self.CMD_CONST_ = CMD_CONST_input
        self.CMD_CONFIG_COUNT_PER_ITER_ = CMD_CONFIG_COUNT_PER_ITER_input
        self.CMD_CONFIG_TOTAL_CTRL_COUNT_ = CMD_CONFIG_TOTAL_CTRL_COUNT_input

        self.CMD_CONFIG_PROLOGUE_FU_ = CMD_CONFIG_PROLOGUE_FU_input
        self.CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_ = CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input
        self.CMD_CONFIG_PROLOGUE_FU_CROSSBAR_ = CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input

        self.CMD_LAUNCH_ = CMD_LAUNCH_input

    def sanitize(self, instruction):
        # check 1: take_up_fu function <= 1
        take_up_fu_operation_idx = _take_up_fu_operation_idx_of(instruction['operations'])

        # check 2: prologue routing crossbar each port consistently either all ignore or not
        routing_xbar_ports_if_prologued = {}
        for operation in instruction['operations']:
            count = operation['invalid_iterations']

            # for reg -> port
            if not _is_take_up_fu_operation(operation):
                if len(operation['src_operands']) != 1:
                    raise ValueError("Not take up fu operation must have exactly one source operand, panic in instruction ", instruction, " at operation ", operation)
                src_operand = operation['src_operands'][0]
                if _type(src_operand) == 'REG':
                    cluster_no = _reg_cluster_no_of(src_operand)
                    idd = f"R{cluster_no}"
                    # print (f"Check prologue for reg operand {src_operand['operand']} in operation {operation}, cluster_no {cluster_no}, idd {idd}")
                    if idd in routing_xbar_ports_if_prologued:
                        if routing_xbar_ports_if_prologued[idd] != count:
                            raise ValueError("Routing crossbar ports must be consistently either all ignore or not, panic in instruction ", instruction)
                    else:
                        routing_xbar_ports_if_prologued[idd] = count

            for src_operand in operation['src_operands']:
                if _type(src_operand) == 'PORT':
                    port_name = src_operand['operand']
                    if port_name in routing_xbar_ports_if_prologued:
                        # Take the max count for this port across all operations
                        routing_xbar_ports_if_prologued[port_name] = max(routing_xbar_ports_if_prologued[port_name], count)
                    else:
                        routing_xbar_ports_if_prologued[port_name] = count

        # check 3: all the time_steps are aligned with the index_per_ii
        for operation in instruction['operations']:
            if operation['time_step'] % self.ii != instruction['index_per_ii']:
                raise ValueError("Time step is not aligned with index per ii, panic in instruction ", instruction, " at operation ", operation)

        return routing_xbar_ports_if_prologued


    def makePrologueOperationPackets(self, operation):
        res = []
        # make prologue packets for the operation
        if _is_take_up_fu_operation(operation):
            # prologue FU to ignore this packet
            count = operation.get('invalid_iterations', 1)
            res.append(self.makePrologueFUPackets(operation['time_step'], count))
            # also need to prologue the FU Output routing crossbar
            res.append(self.makePrologueFUCrossbarPackets(operation['time_step']))

        # src operands' prologues are not here, avoid repetition.
        # for src_operand in operation['src_operands']:
        #     if _type(src_operand) == 'PORT':
        #         res.append(self.makePrologueRoutingCrossbarPackets(operation['time_step'], direction_to_idx(src_operand['operand']) + 1))

        return res


    def makePrologueFUPackets(self, timestep, count=1):
        # make prologue FU packet with given prologue count
        return self.IntraCgraPktType(0, self.id_,
                                     payload = self.CgraPayloadType(self.CMD_CONFIG_PROLOGUE_FU_, ctrl_addr = self.CtrlAddrType(timestep % self.ii),
                                                                     data = self.DataType(count, 1)))

    def makePrologueRoutingCrossbarPackets(self, timestep, routing_xbar_idx, count=1):
        return self.IntraCgraPktType(0, self.id_,
                                     payload = self.CgraPayloadType(self.CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_, ctrl_addr = self.CtrlAddrType(timestep % self.ii),
                                                                     ctrl = self.CtrlType(routing_xbar_outport = [self.TileInType(routing_xbar_idx)] + [self.TileInType(0)] * 7),
                                                                     data = self.DataType(count, 1)))
    def makePrologueFUCrossbarPackets(self, timestep, count=1):
        return self.IntraCgraPktType(0, self.id_,
                                     payload = self.CgraPayloadType(self.CMD_CONFIG_PROLOGUE_FU_CROSSBAR_, ctrl_addr = self.CtrlAddrType(timestep % self.ii),
                                                                     ctrl = self.CtrlType(fu_xbar_outport = [self.FuOutType(0)] * 8),
                                                                     # WARN:by now, only support one result for each operation
                                                                     data = self.DataType(count, 1)))
    def expandInstructionsByTimeStep(self):
        expanded = []
        for instruction in self.instructions:
            grouped_ops = {}
            for operation in instruction['operations']:
                ctrl_addr = operation['time_step'] % self.ii
                expanded_operation = dict(operation)
                grouped_ops.setdefault(ctrl_addr, []).append(expanded_operation)

            for ctrl_addr in sorted(grouped_ops):
                expanded_instruction = dict(instruction)
                expanded_instruction['index_per_ii'] = ctrl_addr
                expanded_instruction['operations'] = grouped_ops[ctrl_addr]
                expanded.append(expanded_instruction)
        return expanded

    def makeTileSignals(self):
        consts = []
        all_signals = []
        all_instruction_signals = []
        prologue_signals = []
        has_addrs = []
        instructions = self.expandInstructionsByTimeStep() \
            if self.use_time_step_ctrl_addr else self.instructions

        local_accumulator_regs = set()
        if self.accumulate_add_to_src_reg:
            for instruction in instructions:
                for operation in instruction['operations']:
                    if operation.get('opcode') != 'ADD':
                        continue
                    src_operands = operation.get('src_operands', [])
                    dst_operands = operation.get('dst_operands', [])
                    if any(_type(operand) == 'REG' for operand in dst_operands):
                        continue
                    for operand in src_operands:
                        if _type(operand) == 'REG':
                            local_accumulator_regs.add(operand['operand'])

        if local_accumulator_regs:
            used_regs = set()
            for instruction in instructions:
                for operation in instruction['operations']:
                    for operand in operation.get('src_operands', []):
                        if _type(operand) == 'REG':
                            used_regs.add(operand['operand'])
                    for operand in operation.get('dst_operands', []):
                        if _type(operand) == 'REG':
                            used_regs.add(operand['operand'])

            scratch_for_acc = {}
            for reg_name in local_accumulator_regs:
                cluster_base = (int(reg_name[1:]) // REG_CLUSTER_SIZE) * REG_CLUSTER_SIZE
                for reg_idx in range(cluster_base + REG_CLUSTER_SIZE - 1,
                                     cluster_base - 1,
                                     -1):
                    candidate = f"${reg_idx}"
                    if candidate != reg_name and candidate not in used_regs:
                        scratch_for_acc[reg_name] = candidate
                        used_regs.add(candidate)
                        break
                if reg_name not in scratch_for_acc:
                    raise ValueError(
                        f"No scratch register available to drain accumulator feedback for {reg_name}")

            filtered_instructions = []
            for instruction in instructions:
                filtered_ops = []
                for operation in instruction['operations']:
                    src_operands = operation.get('src_operands', [])
                    dst_operands = operation.get('dst_operands', [])
                    is_external_acc_feedback = \
                        operation.get('opcode') == 'DATA_MOV' and \
                        len(src_operands) == 1 and \
                        _type(src_operands[0]) == 'PORT' and \
                        any(_type(dst) == 'REG' and
                            dst['operand'] in local_accumulator_regs
                            for dst in dst_operands)
                    if is_external_acc_feedback:
                        drain_operation = dict(operation)
                        drain_dsts = []
                        for dst in dst_operands:
                            if _type(dst) == 'REG' and \
                               dst['operand'] in local_accumulator_regs:
                                scratch_dst = dict(dst)
                                scratch_dst['operand'] = \
                                    scratch_for_acc[dst['operand']]
                                drain_dsts.append(scratch_dst)
                            else:
                                drain_dsts.append(dst)
                        drain_operation['dst_operands'] = drain_dsts
                        filtered_ops.append(drain_operation)
                    else:
                        filtered_ops.append(operation)

                if filtered_ops:
                    filtered_instruction = dict(instruction)
                    filtered_instruction['operations'] = filtered_ops
                    filtered_instructions.append(filtered_instruction)
            instructions = filtered_instructions

        used_addrs = {
            instruction['index_per_ii']
            for instruction in instructions
        }

        shifted_ctrl_addrs = {}

        def is_shiftable_port_to_port(instruction):
            for operation in instruction['operations']:
                if operation.get('opcode') != 'DATA_MOV':
                    return False
                src_operands = operation.get('src_operands', [])
                dst_operands = operation.get('dst_operands', [])
                if len(src_operands) != 1 or _type(src_operands[0]) != 'PORT':
                    return False
                if not dst_operands or any(_type(dst) != 'PORT' for dst in dst_operands):
                    return False
            return True

        for instruction in instructions:
            ctrl_addr = instruction['index_per_ii']
            shifted_addr = (ctrl_addr + 1) % self.ii
            if False and \
               int(self.id_) == 9 and \
               is_shiftable_port_to_port(instruction) and \
               shifted_addr not in used_addrs:
                shifted_ctrl_addrs[id(instruction)] = shifted_addr
            else:
                shifted_ctrl_addrs[id(instruction)] = ctrl_addr

        # build all the instruction signals and get all the const
        import sys
        for instr_idx_dbg, instruction in enumerate(instructions):
            # Suppress verbose per-instruction output for speed
            pass
             # do necessary sanitization
            prologued_ports = self.sanitize(instruction)
            ctrl_addr = shifted_ctrl_addrs[id(instruction)]
            #print(prologued_ports)

            # only when the take_up_fu_op exists and no prologue, then no prologue
            prologue_fu = False
            max_invalid_iterations = 0

            for operation in instruction['operations']:
                if operation['invalid_iterations'] > 0:
                    prologue_fu = True
                    max_invalid_iterations = max(max_invalid_iterations, operation['invalid_iterations'])

            for operation in instruction['operations']:
                if _is_take_up_fu_operation(operation) and operation['invalid_iterations'] == 0:
                    prologue_fu = False

            # only non-taken prologue -> still need prologue FU
            # only taken prologue -> need prologue FU
            #  +--------------------+----------+--------------+
            #  | non-taken \ taken  | prologue | not prologue |
            #  +--------------------+----------+--------------+
            #  | prologue           |   yes    |    no        |
            #  | not prologue       |   yes    |    no        |
            #  +--------------------+----------+--------------+

            if prologue_fu:
                prologue_signals.append(self.makePrologueFUPackets(ctrl_addr, max_invalid_iterations))
                prologue_signals.append(self.makePrologueFUCrossbarPackets(ctrl_addr, max_invalid_iterations))

            # add all routing crossbar prologues for all the operations (can not be op by op to avoid repetition)
            for port_name, count in prologued_ports.items():
                if count > 0:
                    if port_name.startswith('R'):
                        cluster_no = int(port_name[1:])
                        routing_xbar_idx = cluster_no + 4 - 1
                    else:
                        routing_xbar_idx = direction_to_idx(port_name)
                    prologue_signals.append(self.makePrologueRoutingCrossbarPackets(ctrl_addr, routing_xbar_idx + 1, count))

            # add an addtional prologue packet for PHI_CONST / PHI_START operation
            for operation in instruction['operations']:
                if operation['opcode'] == 'PHI_CONST' or operation['opcode'] == "PHI_START":
                    # only src1 will be prologued once, and only if it is a port, it needs a routing crossbar prologue
                    if _type(operation['src_operands'][1]) == 'PORT':
                        routing_xbar_idx = direction_to_idx(operation['src_operands'][1]['operand'])
                        prologue_signals.append(self.makePrologueRoutingCrossbarPackets(operation['time_step'], routing_xbar_idx + 1))

            # mark this time slot is not empty
            has_addrs.append(ctrl_addr)

            instruction_signals = InstructionSignals(
                id_ = self.id_,
                operations = instruction['operations'],
                opcode_in_EIR = instruction['operations'][0]['opcode'], # transient TODO: make it general
                ctrl_addr = ctrl_addr,
                IntraCgraPktType = self.IntraCgraPktType,
                CgraPayloadType = self.CgraPayloadType,
                TileInType = self.TileInType,
                FuOutType = self.FuOutType,
                CMD_CONFIG_input = self.CMD_CONFIG_,
                CtrlType = self.CtrlType,
                FuInType = self.FuInType,
                B1Type = self.B1Type,
                B2Type = self.B2Type,
                RegIdxType = self.RegIdxType,
                CtrlAddrType = self.CtrlAddrType,
                accumulate_add_to_src_reg = self.accumulate_add_to_src_reg)
            all_instruction_signals.append(instruction_signals)

            const = instruction_signals.buildCtrlPkt()
            if const is not None:
                consts.extend(const)

        print(f"[Core {self.id_}] All {len(instructions)} instructions processed, building const signals...")
        sys.stdout.flush()

        # make the const signals
        #print("\n\n\n\n\n\n\n\n\n\n\n\n\n")
        # ConstQueueDynamicRTL consumes constants in controller execution order
        # (the order CONFIG packets are generated), not in scheduled time_step
        # order. Some schedules have non-monotonic time_steps across
        # index_per_ii slots, so sorting here misaligns const-using ops.
        #print(consts)
        for idx, (const_operand, _) in enumerate(consts):
            operand_str = const_operand['operand']
            if operand_str.startswith('#'):
                const_val = int(operand_str[1:])
            elif operand_str.startswith('arg'):
                # Function argument: look up in arg_map
                const_val = self.arg_map.get(operand_str, 0)
            else:
                const_val = int(operand_str)
            const_pkt = self.IntraCgraPktType(0, self.id_,
                                              payload = self.CgraPayloadType(self.CMD_CONST_,
                                                                             data = self.DataType(const_val, 1)))
            all_signals.append(const_pkt)

        # If any instruction uses 2D GEP, send stride configuration packet
        if self.gep_stride is not None:
            has_gep_2d = False
            for instruction in instructions:
                for operation in instruction['operations']:
                    if operation['opcode'] == 'GEP' and _is_take_up_fu_operation(operation):
                        try:
                            src_operands = operation['src_operands']
                        except:
                            src_operands = []
                        non_imm_count = sum(1 for op in src_operands if _type(op) != 'IMM')
                        if non_imm_count >= 2:
                            has_gep_2d = True
                            break
                if has_gep_2d:
                    break
            if has_gep_2d:
                from lib.cmd_type import CMD_CONFIG_GEP_STRIDE
                gep_stride_pkt = self.IntraCgraPktType(0, self.id_,
                    payload = self.CgraPayloadType(CMD_CONFIG_GEP_STRIDE,
                                                   data = self.DataType(self.gep_stride, 1)))
                all_signals.append(gep_stride_pkt)

        print(f"[Core {self.id_}] Building pre-config and main packets...")
        sys.stdout.flush()

        # make the pre-configuration
        ii_pkt = self.IntraCgraPktType(0, self.id_,
                                       payload = self.CgraPayloadType(self.CMD_CONFIG_COUNT_PER_ITER_,
                                                                      data = self.DataType(self.ii, 1)))
        all_signals.append(ii_pkt)
        loop_times_pkt = self.IntraCgraPktType(0, self.id_,
                                               payload = self.CgraPayloadType(self.CMD_CONFIG_TOTAL_CTRL_COUNT_,
                                                                              data = self.DataType(self.loop_times, 1)))
        all_signals.append(loop_times_pkt)


        main_signals = {}
        # make the main packets
        for instruction_signals in all_instruction_signals:
            pkt = instruction_signals.makeCtrlPkt()
            main_signals[int(pkt.payload.ctrl_addr)] = pkt


        # fill the non-existent timesteps with NAH packets

        filled_main_signals = []
        for timestep in range(self.ii):
            if timestep not in has_addrs:
                NAH_SIGNAL = self.IntraCgraPktType(0, self.id_,
                            payload = self.CgraPayloadType(self.CMD_CONFIG_, ctrl_addr = self.CtrlAddrType(timestep),
                                                      ctrl = self.CtrlType(OPT_NAH,
                                                                      [self.FuInType(i) for i in range(1, 5)],
                                                                      [self.TileInType(0)] * 8,
                                                                      [self.FuOutType(0)] * 8)))
                filled_main_signals.append(NAH_SIGNAL)
            else:
                filled_main_signals.append(main_signals[timestep])


        all_signals.extend(filled_main_signals)

        # make prologue packets
        # re-order the prologue packets
        '''
        ordered_prologue_signals = []
        for pkt in prologue_signals:
            if pkt.cmd == self.CMD_CONFIG_PROLOGUE_FU_:
                ordered_prologue_signals.append(pkt)
        for pkt in prologue_signals:
            if pkt.cmd == self.CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_:
                ordered_prologue_signals.append(pkt)
        for pkt in prologue_signals:
            if pkt.cmd == self.CMD_CONFIG_PROLOGUE_FU_CROSSBAR_:
                ordered_prologue_signals.append(pkt)

        all_signals.extend(ordered_prologue_signals)
        '''
        all_signals.extend(prologue_signals)
        # make the launch packet
        launch_pkt = self.IntraCgraPktType(0, self.id_,
                                           payload = self.CgraPayloadType(self.CMD_LAUNCH_))
        all_signals.append(launch_pkt)

        print(f"[Core {self.id_}] makeTileSignals() DONE, {len(all_signals)} total signals")
        sys.stdout.flush()

        return all_signals
class ScriptFactory:
    FromFu = 0
    FromRouting = 1

    def __init__(self,
                 path,
                 CtrlType,
                 IntraCgraPktType,
                 CgraPayloadType,
                 TileInType,
                 FuOutType,
                 CMD_CONFIG_input,
                 FuInType,
                 ii,
                 loop_times,
                 CMD_CONST_input,
                 CMD_CONFIG_COUNT_PER_ITER_input,
                 CMD_CONFIG_TOTAL_CTRL_COUNT_input,
                 CMD_CONFIG_PROLOGUE_FU_input,
                 CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input,
                 CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input,
                 CMD_LAUNCH_input,
                 DataType,
                 B1Type,
                 B2Type,
                 RegIdxType,
                 CtrlAddrType,
                 DataAddrType,
                 num_registers_per_reg_bank=None,
                 arg_map=None,
                 gep_stride=None,
                 use_time_step_ctrl_addr=False,
                 accumulate_add_to_src_reg=False):
        # Allow overriding the default register cluster size.
        global REG_CLUSTER_SIZE
        if num_registers_per_reg_bank is not None:
            REG_CLUSTER_SIZE = int(num_registers_per_reg_bank)
        # arg_map: dict mapping function argument names (e.g. "arg6") to
        # integer values (e.g. base addresses). Used for GEP operations
        # that reference function parameters.
        self.arg_map = arg_map if arg_map is not None else {}
        self.gep_stride = gep_stride  # stride for 2D GEP operations
        self.use_time_step_ctrl_addr = use_time_step_ctrl_addr
        self.accumulate_add_to_src_reg = accumulate_add_to_src_reg
        self.yaml_struct = yaml.load(open(path, 'r'), Loader=yaml.FullLoader)
        self.path = path
        self.CtrlType = CtrlType
        self.IntraCgraPktType = IntraCgraPktType
        self.CgraPayloadType = CgraPayloadType
        self.TileInType = TileInType
        self.FuOutType = FuOutType
        self.CMD_CONFIG_ = CMD_CONFIG_input
        self.FuInType = FuInType
        self.ii = ii
        self.loop_times = loop_times
        self.CMD_CONST_ = CMD_CONST_input
        self.CMD_CONFIG_COUNT_PER_ITER_ = CMD_CONFIG_COUNT_PER_ITER_input
        self.CMD_CONFIG_TOTAL_CTRL_COUNT_ = CMD_CONFIG_TOTAL_CTRL_COUNT_input
        self.CMD_CONFIG_PROLOGUE_FU_ = CMD_CONFIG_PROLOGUE_FU_input
        self.CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_ = CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input
        self.CMD_CONFIG_PROLOGUE_FU_CROSSBAR_ = CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input
        self.CMD_LAUNCH_ = CMD_LAUNCH_input
        self.DataType = DataType
        self.B1Type = B1Type
        self.B2Type = B2Type
        self.RegIdxType = RegIdxType
        self.CtrlAddrType = CtrlAddrType
        self.DataAddrType = DataAddrType

    def makeVectorCGRAPkts(self):

        pkts = {}
        cores = self.yaml_struct['array_config']['cores']


        for core in cores:
            x, y = core['column'], core['row']
            entry = core['entries'][0]
            instructions = entry['instructions']
            id_ = core['core_id']

            import sys
            print(f"\n>>> makeVectorCGRAPkts: Starting Core {id_} at ({x},{y}) with {len(instructions)} instructions")
            sys.stdout.flush()

            tile_signals = TileSignals(
                CtrlType = self.CtrlType,
                IntraCgraPktType = self.IntraCgraPktType,
                CgraPayloadType = self.CgraPayloadType,
                TileInType = self.TileInType,
                FuOutType = self.FuOutType,
                CMD_CONFIG_input = self.CMD_CONFIG_,
                FuInType = self.FuInType,
                id_ = id_,
                loop_times = self.loop_times,
                ii = self.ii,
                instructions = instructions,
                CMD_CONST_input = self.CMD_CONST_,
                CMD_CONFIG_COUNT_PER_ITER_input = self.CMD_CONFIG_COUNT_PER_ITER_,
                CMD_CONFIG_TOTAL_CTRL_COUNT_input = self.CMD_CONFIG_TOTAL_CTRL_COUNT_,
                CMD_CONFIG_PROLOGUE_FU_input = self.CMD_CONFIG_PROLOGUE_FU_,
                CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input = self.CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_,
                CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input = self.CMD_CONFIG_PROLOGUE_FU_CROSSBAR_,
                CMD_LAUNCH_input = self.CMD_LAUNCH_,
                DataType = self.DataType,
                B1Type = self.B1Type,
                B2Type = self.B2Type,
                RegIdxType = self.RegIdxType,
                CtrlAddrType = self.CtrlAddrType,
                DataAddrType = self.DataAddrType,
                arg_map = self.arg_map,
                gep_stride = self.gep_stride,
                use_time_step_ctrl_addr = self.use_time_step_ctrl_addr,
                accumulate_add_to_src_reg = self.accumulate_add_to_src_reg,
                )
            tile_signals = tile_signals.makeTileSignals()
            pkts[(x, y)] = tile_signals
            print(f">>> makeVectorCGRAPkts: Core {id_} DONE")
            sys.stdout.flush()

        print(">>> makeVectorCGRAPkts: ALL CORES DONE")
        sys.stdout.flush()
        return pkts

from validation.test.dummy import *

if __name__ == "__main__":
    print("Test the Basic Functionality of the ScriptFactory")

    script_factory = ScriptFactory(
        path = "./validation/test/gemm/gemm.yaml",
        CtrlType = CtrlTypeDummy,
        IntraCgraPktType = IntraCgraPktTypeDummy,
        CgraPayloadType = CgraPayloadTypeDummy,
        TileInType = TileInTypeDummy,
        FuOutType = FuOutTypeDummy,
        CMD_CONFIG_input = CMD_CONFIG_Dummy(),
        FuInType = FuInTypeDummy,
        ii = 17,
        loop_times = 2,
        CMD_CONST_input = CMD_CONST_Dummy(),
        CMD_CONFIG_COUNT_PER_ITER_input = CMD_CONFIG_COUNT_PER_ITER_Dummy(),
        CMD_CONFIG_TOTAL_CTRL_COUNT_input = CMD_CONFIG_TOTAL_CTRL_COUNT_Dummy(),
        CMD_CONFIG_PROLOGUE_FU_input = CMD_CONFIG_PROLOGUE_FU_Dummy(),
        CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input = CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_Dummy(),
        CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input = CMD_CONFIG_PROLOGUE_FU_CROSSBAR_Dummy(),
        CMD_LAUNCH_input = CMD_LAUNCH_Dummy(),
        DataType = DataTypeDummy,
        B1Type = B1TypeDummy,
        B2Type = B2TypeDummy,
        RegIdxType = RegIdxTypeDummy,
        CtrlAddrType = CtrlAddrTypeDummy,
        DataAddrType = DataAddrTypeDummy,
    )

    pkts = script_factory.makeVectorCGRAPkts()
    for x, y in pkts:
        print(f"Tile ({x}, {y}):")
        for pkt in pkts[(x, y)]:
            print(pkt)
            print("--------------------------------")
