"""
==========================================================================
script_generator.py
==========================================================================
A translator to translate yaml-formatted IR generated by compiler to the 
packets used in VectorCGRA

Author : Bohan Cui
  Date : Feb 25, 2026
"""

### Usage:
# 1. create factory instance with the types 
# (for the spec of the types, please refer to e.g. cgra/test/CgraRTL_fir_test.py)
# ```
# script_factory = ScriptFactory(
#     path = the_input_yaml,
#     CtrlType = your_CtrlType,
#     IntraCgraPktType = your_IntraCgraPktType,
#     CgraPayloadType = your_CgraPayloadType,
#     TileInType = your_TileInType,
#     FuOutType = your_FuOutType,
#     CMD_CONFIG_input = your_CMD_CONFIG_input,
#     FuInType = your_FuInType,
#     ii = your_ii,
#     loop_times = your_loop_times,
#     CMD_CONST_input = your_CMD_CONST_input,
#     CMD_CONFIG_COUNT_PER_ITER_input = your_CMD_CONFIG_COUNT_PER_ITER_input,
#     CMD_CONFIG_TOTAL_CTRL_COUNT_input = your_CMD_CONFIG_TOTAL_CTRL_COUNT_input,
#     CMD_CONFIG_PROLOGUE_FU_input = your_CMD_CONFIG_PROLOGUE_FU_input,
#     CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input = your_CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input,
#     CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input = your_CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input,
#     CMD_LAUNCH_input = your_CMD_LAUNCH_input,
#     DataType = your_DataType,
#     B1Type = your_B1Type,
#     B2Type = your_B2Type,
#     RegIdxType = your_RegIdxType,
#     CtrlAddrType = your_CtrlAddrType,
#     DataAddrType = your_DataAddrType,
# )
# ```
# 2. make the packets
# pkts = script_factory.makeVectorCGRAPkts()

import sys
import os
import yaml

# Add project root to path to allow imports from lib
# Get the absolute path of this file
_script_dir = os.path.dirname(os.path.abspath(__file__))
# Get the project root (parent of validation directory)
project_root = os.path.dirname(_script_dir)
# Normalize the path to handle any symlinks or relative path issues
project_root = os.path.normpath(os.path.abspath(project_root))

if project_root not in sys.path:
    sys.path.insert(0, project_root)

from lib.opt_type import *

# Global configuration for register cluster size (number of registers per cluster).
# This can be overridden by ScriptFactory initialization.
REG_CLUSTER_SIZE = 8

yaml_to_VectorCGRA_map = {
    "CONSTANT": OPT_CONST, # ?
    "ADD": OPT_ADD,
    "MUL": OPT_MUL,
    "SUB": OPT_SUB,
    "DIV": OPT_DIV,
    "REM": OPT_REM,
    "FADD": OPT_FADD,
    "FSUB": OPT_FSUB,
    "FMUL": OPT_FMUL,
    "FDIV": None, # ?
    "OR": OPT_OR,
    "AND": OPT_AND,
    "NOT": OPT_NOT,
    "ICMP_EQ": OPT_EQ, # ?
    "ICMP_SGE": OPT_GTE,
    "ICMP_SGT": OPT_GT,
    "FCMP": None, # ?
    "SEL": OPT_SEL,
    "CAST": None, # ?
    "SEXT": OPT_PAS, # no sext, just a fake one.
    "ZEXT": OPT_PAS, # zero extension treated as pass-through
    "SHL": OPT_LLS,
    "VFMUL": None, # ?
    "FADD_FADD": None, #?
    "FMUL_FADD": None, #?
    "DATA_MOV": None, #?
    "CTRL_MOV": None, #?
    "RESERVE": None, #?
    "GRANT_PREDICATE": OPT_GRT_PRED,
    "GRANT_ALWAYS": None, #?
    "GRANT_ONCE": OPT_GRT_ONCE, #?
    "PHI": OPT_PHI,
    "LOOP_CONTROL": None, #?
    "PHI_CONST": OPT_PHI_CONST, 
    "PHI_START": OPT_PHI_START,
    
    "GEP": OPT_ADD, # base + index; with base=#0 this reduces to index (no GepRTL in FuList)
    
    "ICMP_ULT": OPT_LT, # unsigned less-than: in0 < in1
    
    "RETURN": OPT_RET,
    "RETURN_VALUE": OPT_RET,
    "RETURN_VOID": OPT_RET_VOID,
    "LDD": OPT_LD,
    "LOAD": OPT_LD,
    "STORE": OPT_STR,
    
    "NE": OPT_NE,
    "MUL_ADD": OPT_MUL_ADD,
    "DATA_MOV": OPT_PAS
    
}

yaml_to_VectorCGRA_map_const = {
    "CONSTANT": OPT_CONST,
    "NE": OPT_NE_CONST,
    "ADD": OPT_ADD_CONST,
    "MUL_ADD": OPT_MUL_CONST_ADD,
    "MUL": OPT_MUL_CONST,
    "DIV": OPT_DIV_CONST,
    "GEP": OPT_ADD_CONST, # base(const=0) + index(in0); reduces to index
    "AND": OPT_AND_CONST,
    "OR": OPT_OR_CONST,
    "ICMP_EQ": OPT_EQ_CONST,
    "ICMP_SGE": OPT_GTE_CONST,
    "ICMP_SGT": OPT_GT_CONST,
    "ICMP_ULT": OPT_LT_CONST, # unsigned less-than with const: in0 < const

    "GRANT_ONCE": OPT_GRT_ONCE_CONST,
    "SHL": OPT_LLS_CONST,
}



def _type(Operand):
    impl = Operand['operand']
    if impl[0] == "$":
        return 'REG'
    elif impl.upper() in ['NORTH', 'SOUTH', 'WEST', 'EAST', 'SOUTHEAST', 'SOUTHWEST', 'NORTHWEST', 'NORTHEAST']:
        return 'PORT'
    else:
        return 'IMM'
    
def direction_to_idx(direction):
    if direction == 'NORTH':
        return 0
    elif direction == 'SOUTH':
        return 1
    elif direction == 'WEST':
        return 2
    elif direction == 'EAST':
        return 3
    else:
        raise ValueError("Invalid direction: ", direction)

def _is_take_up_fu_operation(operation):
    if operation['opcode'] == 'MOV' or operation['opcode'] == 'DATA_MOV' or operation['opcode'] == 'CTRL_MOV':
        if len(operation['src_operands']) != 1:
            raise ValueError("MOV operation must have exactly one source operand")
        elif _type(operation['src_operands'][0]) == 'PORT':
            return False # By now, only Port -> Port and Port -> Reg are not take up fu operations
        else:
            # REG -> PORT only: can be handled by FU output crossbar routing
            # without occupying the FU, so treat as not-take-up-fu.
            dst_operands = operation.get('dst_operands', [])
            if dst_operands and all(_type(d) == 'PORT' for d in dst_operands):
                return False
            return True
    else:
        return True
    
def _take_up_fu_operation_idx_of(operations: list):
    # check if there is only < 1 take up fu operation, if 1, return the idx, if > 1, raise error, if 0, return -1
    take_up_fu_operation_idx = -1
    for idx, operation in enumerate(operations):
        if _is_take_up_fu_operation(operation):
            if take_up_fu_operation_idx != -1:
                raise ValueError("Only one take up fu operation is allowed, panic in instruction ", operations)
            take_up_fu_operation_idx = idx
    return take_up_fu_operation_idx
    
def _reg_cluster_no_of(operand): # start from 1
    impl = operand['operand']
    if impl[0] == "$":
        return int(impl[1:]) // REG_CLUSTER_SIZE + 1
    else:
        raise ValueError("Operand is not a register")

def _reg_cluster_intra_index_of(operand):
    impl = operand['operand']
    if impl[0] == "$":
        return int(impl[1:]) % REG_CLUSTER_SIZE
    else:
        raise ValueError("Operand is not a register")

def print_instruction(instruction):
    print(f"Instruction: {[operation['opcode'] for operation in instruction['operations']]}")

FROM_NOWHERE = 0
FROM_PORT = 1
FROM_FU = 2
FROM_CONSTANT_QUEUE = 3 # not used by now

OPR_FROM_PORT = 0          # read_reg_towards = READ_TOWARDS_NOTHING (0)
OPR_FROM_REGISTER = 1      # read_reg_towards = READ_TOWARDS_FU (1)
OPR_FROM_REGISTER_TO_XBAR = 2  # read_reg_towards = READ_TOWARDS_ROUTING_XBAR (2)
OPR_FROM_REGISTER_TO_BOTH = 3  # read_reg_towards = READ_TOWARDS_BOTH (3)

# Number of tile input ports (N, S, W, E) — matches num_tile_inports in hardware
_NUM_TILE_INPORTS = 4

class InstructionSignals:
    # to make signal of single instruction
    def __init__(self, 
                 # input
                 id_,
                 operations,
                 opcode_in_EIR,
                 ctrl_addr,
                 # types
                 IntraCgraPktType, 
                 CgraPayloadType, 
                 TileInType, 
                 FuOutType, 
                 CMD_CONFIG_input, 
                 CtrlType,
                 FuInType,
                 B1Type,
                 B2Type,
                 RegIdxType,
                 CtrlAddrType):
        # types
        self.IntraCgraPktType = IntraCgraPktType
        self.CgraPayloadType = CgraPayloadType
        self.TileInType = TileInType
        self.FuOutType = FuOutType
        self.CMD_CONFIG_ = CMD_CONFIG_input
        self.CtrlType = CtrlType
        self.FuInType = FuInType
        self.B1Type = B1Type
        self.B2Type = B2Type
        self.RegIdxType = RegIdxType
        self.CtrlAddrType = CtrlAddrType
        
        # inputs
        self.id_ = id_
        self.operations = operations
        self.OpCode = opcode_in_EIR
        self.ctrl_addr = ctrl_addr
        
        # States
        self.TileInParams = [-1, -1, -1, -1, -1, -1, -1, -1]
        self.FuOutParams = [-1, -1, -1, -1, -1, -1, -1, -1]
        self.read_from_reg = [-1, -1, -1, -1]
        self.read_from_reg_idx = [-1, -1, -1, -1]
        self.write_to_reg = [-1, -1, -1, -1]
        self.write_to_reg_idx = [-1, -1, -1, -1]
        self.shuffle_fu_operand_input_index = [-1, -1, -1, -1]

        
    def buildCtrlPkt(self) -> list: # return the const needed to put into the const queue
        # you must call buildCtrlPkt before makeCtrlPkt, and for a Tile's signal, you must call buildCtrlPkt in order.
        try:
            
            # 1. Find take up fu operation
            take_up_fu_operation_idx = _take_up_fu_operation_idx_of(self.operations)
            
            if take_up_fu_operation_idx == -1:
                print("No take up fu operation found, just take the first.")
                take_up_fu_operation_idx = 0
                take_up_fu_operation = "NAH"
                self.OpCode = OPT_NAH
            else:
                print("Take_up_fu_operation: ", self.operations[take_up_fu_operation_idx])
                take_up_fu_operation = self.operations[take_up_fu_operation_idx]
                # only take up fu can be const
                has_const = False
                # if has src_operands, check if has const
                try:
                    src_operands = take_up_fu_operation['src_operands']
                except Exception as e:
                    src_operands = []
                for src_operand in src_operands:
                    if _type(src_operand) == 'IMM':
                        has_const = True
                        break 
                
                #if take_up_fu_operation['opcode'] == 'PHI_CONST' or take_up_fu_operation['opcode'] == 'CONSTANT':
                    #has_const = False # PHI_CONST and CONSTANT are special.
            
                if has_const:
                    self.OpCode = yaml_to_VectorCGRA_map_const[self.operations[take_up_fu_operation_idx]['opcode']]
                else:
                    self.OpCode = yaml_to_VectorCGRA_map[self.operations[take_up_fu_operation_idx]['opcode']]

            const_operands = []

            # Process non-take-up-fu operations first to reserve their
            # TileInParams slots before take-up-fu port lane allocation.
            ordered_operations = sorted(
                self.operations,
                key=lambda op: 0 if not _is_take_up_fu_operation(op) else 1)

            for operation in ordered_operations: # for each operation in the instruction

                print("\n Operation: ", operation)

                operation_opcode = operation['opcode']
                try:
                    src_operands = operation['src_operands'].copy()
                    if operation_opcode == 'STORE' and len(src_operands) >= 2:
                        # HW expects address in0 and data in1, but YAML gives [data, addr]
                        src_operands[0], src_operands[1] = src_operands[1], src_operands[0]
                except Exception as e:
                    src_operands = []
                try:
                    dst_operands = operation['dst_operands']
                except Exception as e:
                    dst_operands = []

                # find all the const
                for index, src_operand in enumerate(src_operands):
                    if _type(src_operand) == 'IMM':
                        const_operands.append(src_operand)
                        # delete it from the src_operands since it is implicit in vectorCGRA
                        del src_operands[index]

                # for not_take_up_fu_operation
                if not _is_take_up_fu_operation(operation):

                    if len(src_operands) != 1:
                        raise ValueError(f"Not take up fu operation {operation} must have exactly one source operand.")

                    src_operand = src_operands[0]

                    # REG -> PORT: route via routing_crossbar.
                    # The register cluster output is fed directly into the routing
                    # crossbar as an additional input (input index = _NUM_TILE_INPORTS +
                    # (cluster_no - 1)).  We configure the routing crossbar output for
                    # the destination port to select that input, and set
                    # read_reg_towards = READ_TOWARDS_ROUTING_XBAR (2) so the register
                    # bank drives send_data_to_routing_crossbar.val = 1.
                    if _type(src_operand) == 'REG':
                        cluster_no = _reg_cluster_no_of(src_operand)   # 1-indexed
                        intra_index = _reg_cluster_intra_index_of(src_operand)
                        # routing_crossbar input index (0-based) for this cluster:
                        #   _NUM_TILE_INPORTS + (cluster_no - 1)
                        # crossbar config value (1-indexed, 0 = no-connect):
                        #   _NUM_TILE_INPORTS + cluster_no
                        xbar_input_config = _NUM_TILE_INPORTS + cluster_no
                        for dst_operand in dst_operands:
                            if _type(dst_operand) == 'PORT':
                                if dst_operand['operand'] == 'NORTH':
                                    port_out_xbar_idx = 0
                                elif dst_operand['operand'] == 'SOUTH':
                                    port_out_xbar_idx = 1
                                elif dst_operand['operand'] == 'WEST':
                                    port_out_xbar_idx = 2
                                elif dst_operand['operand'] == 'EAST':
                                    port_out_xbar_idx = 3
                                else:
                                    raise ValueError(f"Unknown PORT direction {dst_operand} in REG->PORT, operation {operation}")
                                if self.TileInParams[port_out_xbar_idx] != -1 and \
                                   self.TileInParams[port_out_xbar_idx] != xbar_input_config:
                                    raise ValueError(f"Collision in routing_crossbar output {port_out_xbar_idx} (REG->PORT), operation {operation}")
                                self.TileInParams[port_out_xbar_idx] = xbar_input_config
                            else:
                                raise ValueError(f"REG->non-PORT dst {dst_operand} classified as not take-up-fu, when translate the operation {operation} to VectorCGRA")
                        # Set read_reg_towards for this cluster so the register bank
                        # drives send_data_to_routing_crossbar.
                        cur = self.read_from_reg[cluster_no - 1]
                        if cur == -1 or cur == OPR_FROM_PORT:
                            self.read_from_reg[cluster_no - 1] = OPR_FROM_REGISTER_TO_XBAR
                        elif cur == OPR_FROM_REGISTER:
                            # Also needed for FU: upgrade to BOTH
                            self.read_from_reg[cluster_no - 1] = OPR_FROM_REGISTER_TO_BOTH
                        # else: already xbar (2) or both (3) — leave as-is
                        if self.read_from_reg_idx[cluster_no - 1] == -1:
                            self.read_from_reg_idx[cluster_no - 1] = intra_index
                        continue

                    if _type(src_operand) != 'PORT':
                        raise ValueError(f"Source operand {src_operand} is not port and be classified not take up fu.")

                    src_direction_idx = direction_to_idx(src_operand['operand'])

                    for index, dst_operand in enumerate(dst_operands):
                        if _type(dst_operand) == 'REG':
                            cluster_no = _reg_cluster_no_of(dst_operand)
                            intra_index = _reg_cluster_intra_index_of(dst_operand)
                            # set the TileInParams
                            if self.TileInParams[cluster_no + 4 - 1] != -1 and self.TileInParams[cluster_no + 4 - 1] != src_direction_idx + 1:
                                raise ValueError(f"Collision when reading from port in TileInParams, when translate the operation {operation} to VectorCGRA")
                            self.TileInParams[cluster_no + 4 - 1] = src_direction_idx + 1

                            if self.write_to_reg_idx[cluster_no - 1] != -1 and self.write_to_reg_idx[cluster_no - 1] != intra_index:
                                raise ValueError(f"Collision when writing to register in write_to_reg_idx, when translate the operation {operation} to VectorCGRA")
                            self.write_to_reg[cluster_no - 1] = FROM_PORT
                            self.write_to_reg_idx[cluster_no - 1] = intra_index
                        elif _type(dst_operand) == 'PORT':
                            if dst_operand['operand'] == 'NORTH':
                                port_out_xbar_idx = 0
                            elif dst_operand['operand'] == 'SOUTH':
                                port_out_xbar_idx = 1
                            elif dst_operand['operand'] == 'WEST':
                                port_out_xbar_idx = 2
                            elif dst_operand['operand'] == 'EAST':
                                port_out_xbar_idx = 3
                            if self.TileInParams[port_out_xbar_idx] != -1 and self.TileInParams[port_out_xbar_idx] != src_direction_idx + 1:
                                raise ValueError(f"Collision in writing to port {dst_operand} in FuOutParams, when translate the operation {operation} to VectorCGRA")
                            self.TileInParams[port_out_xbar_idx] = src_direction_idx + 1 # 1,2,3,4 for N,S,W,E
                        else:
                            raise ValueError(f"Unsupported type of dst operand {dst_operand}, when translate the operation {operation} to VectorCGRA")
                    continue
                             
                
                # reorder the src operands since register has high priority (cause reg can't be shuffled but port can be shuffled)
                # TODO: not complete, actually should also take dst into account
                reordered_src_operands = {}
                for index, src_operand in enumerate(src_operands):
                    if _type(src_operand) == 'REG':
                        reordered_src_operands[index] = src_operand
                for index, src_operand in enumerate(src_operands):
                    if not _type(src_operand) == 'REG':
                        reordered_src_operands[index] = src_operand
                
                for index, src_operand in reordered_src_operands.items():
                    if _type(src_operand) == 'REG':
                        print(f">>> index {index} is REG")
                        cluster_no = _reg_cluster_no_of(src_operand)
                        intra_index = _reg_cluster_intra_index_of(src_operand)
                        # Check if cluster_no is within valid range (1 to num_fu_inports)
                        if cluster_no < 1 or cluster_no > len(self.read_from_reg_idx):
                            raise ValueError(f"Register cluster number {cluster_no} is out of range. Valid range is 1 to {len(self.read_from_reg_idx)} for register {src_operand['operand']} in operation {operation}")
                        # Check if intra_index is within valid range (0 to REG_CLUSTER_SIZE-1)
                        if intra_index < 0 or intra_index >= REG_CLUSTER_SIZE:
                            raise ValueError(f"Register intra index {intra_index} is out of range. Valid range is 0 to {REG_CLUSTER_SIZE-1} for register {src_operand['operand']} in operation {operation}")
                        if self.read_from_reg_idx[cluster_no - 1] != -1 and self.read_from_reg_idx[cluster_no - 1] != intra_index:
                            raise ValueError(f"Collision when reading from register in read_from_reg_idx, when translate the operation {operation} to VectorCGRA")
                        cur = self.read_from_reg[cluster_no - 1]
                        if cur == -1 or cur == OPR_FROM_PORT:
                            self.read_from_reg[cluster_no - 1] = OPR_FROM_REGISTER
                        elif cur == OPR_FROM_REGISTER_TO_XBAR:
                            # Also needed for FU: upgrade to BOTH
                            self.read_from_reg[cluster_no - 1] = OPR_FROM_REGISTER_TO_BOTH
                        elif cur not in (OPR_FROM_REGISTER, OPR_FROM_REGISTER_TO_BOTH):
                            raise ValueError(f"Collision when reading from register in read_from_reg, when translate the operation {operation} to VectorCGRA")
                        self.read_from_reg_idx[cluster_no - 1] = intra_index
                        if self.shuffle_fu_operand_input_index[index] != -1:
                            raise ValueError(f"Collision when reading from register in shuffle_fu_operand_input_index, when translate the operation {operation} to VectorCGRA")
                        self.shuffle_fu_operand_input_index[index] = cluster_no # shuffle the data to the correct inport of the FU from the register
                    if _type(src_operand) == 'PORT':
                        if src_operand['operand'] == 'NORTH':
                            port_in_xbar_idx = 1
                        elif src_operand['operand'] == 'SOUTH':
                            port_in_xbar_idx = 2
                        elif src_operand['operand'] == 'WEST':
                            port_in_xbar_idx = 3
                        elif src_operand['operand'] == 'EAST':
                            port_in_xbar_idx = 4
                            
                        # find an available lane
                        lane = -1
                        for i in range(4):
                            if self.read_from_reg[i] == -1 and self.TileInParams[i + 4] == -1: # if not set the selection, then it could be available
                                lane = i
                                break
                        if lane == -1:
                            raise ValueError(f"No available lane found when reading from port {src_operand} in TileInParams, when translate the operation {operation} to VectorCGRA")
                        else:
                            print(f"Lane {lane} available for port source {src_operand}")
                        if self.TileInParams[lane + 4] != -1:
                            raise ValueError(f"Collision in reading from port in TileInParams, when translate the operation {operation} to VectorCGRA")
                        self.TileInParams[lane + 4] = port_in_xbar_idx
                        self.read_from_reg[lane] = OPR_FROM_PORT
                        # shuffle to the given fu input index
                        if self.shuffle_fu_operand_input_index[index] != -1:
                            raise ValueError(f"Collision when reading from port in shuffle_fu_operand_input_index {self.shuffle_fu_operand_input_index} (want to set opr {index} to {lane}), when translate the operation {operation} to VectorCGRA")
                        self.shuffle_fu_operand_input_index[index] = lane + 1
                        
                    if _type(src_operand) == 'IMM':
                        raise NotImplementedError("IMM src operand is not supported yet")
                    
                for index, dst_operand in enumerate(dst_operands):
                    if _type(dst_operand) == 'REG':
                        cluster_no = _reg_cluster_no_of(dst_operand)
                        intra_index = _reg_cluster_intra_index_of(dst_operand)
                        # Check if cluster_no is within valid range (1 to num_fu_inports)
                        if cluster_no < 1 or cluster_no > len(self.write_to_reg_idx):
                            raise ValueError(f"Register cluster number {cluster_no} is out of range. Valid range is 1 to {len(self.write_to_reg_idx)} for register {dst_operand['operand']} in operation {operation}")
                        # Check if intra_index is within valid range (0 to REG_CLUSTER_SIZE-1)
                        if intra_index < 0 or intra_index >= REG_CLUSTER_SIZE:
                            raise ValueError(f"Register intra index {intra_index} is out of range. Valid range is 0 to {REG_CLUSTER_SIZE-1} for register {dst_operand['operand']} in operation {operation}")
                        if self.write_to_reg_idx[cluster_no - 1] != -1 and self.write_to_reg_idx[cluster_no - 1] != intra_index:
                            raise ValueError(f"Collision when writing to register in write_to_reg_idx, when translate the operation {operation} to VectorCGRA, cluster {cluster_no - 1} originally has intra index {self.write_to_reg_idx[cluster_no - 1]}, but now want to set intra index {intra_index}")
                        self.write_to_reg[cluster_no - 1] = FROM_FU
                        self.write_to_reg_idx[cluster_no - 1] = intra_index
                        if self.FuOutParams[cluster_no + 3] != -1:
                            raise ValueError(f"Collision in writing result to register, when translate the operation {operation} to VectorCGRA")
                        self.FuOutParams[cluster_no + 3] = 1
                    elif _type(dst_operand) == 'PORT':
                        if dst_operand['operand'] == 'NORTH':
                            port_out_xbar_idx = 0
                        elif dst_operand['operand'] == 'SOUTH':
                            port_out_xbar_idx = 1
                        elif dst_operand['operand'] == 'WEST':
                            port_out_xbar_idx = 2
                        elif dst_operand['operand'] == 'EAST':
                            port_out_xbar_idx = 3
                        if self.FuOutParams[port_out_xbar_idx] != -1:
                            raise ValueError(f"Collision in writing to port {dst_operand} in FuOutParams, when translate the operation {operation} to VectorCGRA")
                        print(f">>> FuOutParams[{port_out_xbar_idx}] = {index + 1}")
                        self.FuOutParams[port_out_xbar_idx] = 1 # we do not support multiple results 
                    else:
                        raise ValueError(f"Unsupported type of dst operand {dst_operand}, when translate the operation {operation} to VectorCGRA")
        
        except Exception as e:
            print(f"Error in making ctrl pkt: {e}")
            raise e
            return None
        return const_operands
        
    def makeCtrlPkt(self):
        # make fu_in_code
        for idx, fu_in_code in enumerate(self.shuffle_fu_operand_input_index):
            if fu_in_code == -1:
                self.shuffle_fu_operand_input_index[idx] = idx + 1 # 0 or idle inport of ALU?
        fu_in_code_made = [self.FuInType(x) for x in self.shuffle_fu_operand_input_index] # is it correct?
        
        # make TileIn
        for idx, tile_in_param in enumerate(self.TileInParams):
            if tile_in_param == -1:
                self.TileInParams[idx] = 0
        TileIn_made = [self.TileInType(x) for x in self.TileInParams]
        for idx, fu_out_param in enumerate(self.FuOutParams):
            if fu_out_param == -1:
                self.FuOutParams[idx] = 0
        FuOut_made = [self.FuOutType(x) for x in self.FuOutParams]
        
        # made write reg from code
        for idx, write_to_reg in enumerate(self.write_to_reg):
            if write_to_reg == -1:
                self.write_to_reg[idx] = FROM_NOWHERE
        write_reg_from_made = [self.B2Type(x) for x in self.write_to_reg]
        
        for idx, write_to_reg_idx in enumerate(self.write_to_reg_idx):
            if write_to_reg_idx == -1:
                self.write_to_reg_idx[idx] = 0
        write_reg_idx_made = [self.RegIdxType(x) for x in self.write_to_reg_idx]
        
        # make read reg from code
        for idx, read_from_reg in enumerate(self.read_from_reg):
            if read_from_reg == -1:
                self.read_from_reg[idx] = OPR_FROM_PORT

        # read_reg_towards uses 2-bit type (RegFromType): 0=nothing, 1=FU, 2=routing_xbar, 3=both
        read_reg_towards_made = [self.B2Type(x) for x in self.read_from_reg]
        
        for idx, read_from_reg_idx in enumerate(self.read_from_reg_idx):
            if read_from_reg_idx == -1:
                self.read_from_reg_idx[idx] = 0
        read_reg_idx_made = [self.RegIdxType(x) for x in self.read_from_reg_idx]
        
        # make FuOut
        # CtrlType requires: operation, fu_in, routing_xbar_outport, fu_xbar_outport,
        #                    vector_factor_power, is_last_ctrl, write_reg_from, write_reg_idx,
        #                    read_reg_towards, read_reg_idx
        # Use keyword arguments for optional fields to avoid parameter order issues
        pkt = self.IntraCgraPktType(0, self.id_,
                                    payload = self.CgraPayloadType(self.CMD_CONFIG_,
                                                                    ctrl_addr = self.CtrlAddrType(self.ctrl_addr),
                                                                    ctrl = self.CtrlType(self.OpCode,
                                                                                        fu_in_code_made,
                                                                                        TileIn_made,
                                                                                        FuOut_made,
                                                                                        write_reg_from = write_reg_from_made,
                                                                                        write_reg_idx = write_reg_idx_made,
                                                                                        read_reg_towards = read_reg_towards_made,
                                                                                        read_reg_idx = read_reg_idx_made,
                                                                                        )))
        return pkt

class TileSignals:
    def __init__(self,
                CtrlType, 
                IntraCgraPktType, 
                CgraPayloadType, 
                TileInType, 
                FuOutType, 
                CMD_CONFIG_input, 
                FuInType, 
                id_, 
                loop_times,
                ii,
                instructions,
                CMD_CONST_input,
                CMD_CONFIG_COUNT_PER_ITER_input,
                CMD_CONFIG_TOTAL_CTRL_COUNT_input,
                CMD_CONFIG_PROLOGUE_FU_input,
                CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input,
                CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input,
                CMD_LAUNCH_input,
                DataType,
                B1Type,
                B2Type,
                RegIdxType,
                CtrlAddrType,
                DataAddrType):
        self.CtrlType = CtrlType
        self.IntraCgraPktType = IntraCgraPktType
        self.CgraPayloadType = CgraPayloadType
        self.TileInType = TileInType
        self.FuOutType = FuOutType
        self.CMD_CONFIG_ = CMD_CONFIG_input
        self.FuInType = FuInType
        self.id_ = id_
        self.instructions = instructions
        self.loop_times = loop_times
        self.ii = ii
        self.B1Type = B1Type
        self.B2Type = B2Type
        self.RegIdxType = RegIdxType
        self.DataType = DataType
        self.CtrlAddrType = CtrlAddrType
        self.DataAddrType = DataAddrType
        # constants
        self.CMD_CONST_ = CMD_CONST_input
        self.CMD_CONFIG_COUNT_PER_ITER_ = CMD_CONFIG_COUNT_PER_ITER_input
        self.CMD_CONFIG_TOTAL_CTRL_COUNT_ = CMD_CONFIG_TOTAL_CTRL_COUNT_input
        
        self.CMD_CONFIG_PROLOGUE_FU_ = CMD_CONFIG_PROLOGUE_FU_input
        self.CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_ = CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input
        self.CMD_CONFIG_PROLOGUE_FU_CROSSBAR_ = CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input
        
        self.CMD_LAUNCH_ = CMD_LAUNCH_input
        
    def sanitize(self, instruction):
        # check 1: take_up_fu function <= 1
        take_up_fu_operation_idx = _take_up_fu_operation_idx_of(instruction['operations'])
        
        # check 2: prologue routing crossbar each port consistently either all ignore or not 
        routing_xbar_ports_if_prologued = {}
        for operation in instruction['operations']:
            invalid_cycle = operation['invalid_iterations']
            for src_operand in operation['src_operands']:
                if _type(src_operand) == 'PORT':
                    if src_operand['operand'] in routing_xbar_ports_if_prologued:
                        if routing_xbar_ports_if_prologued[src_operand['operand']] != invalid_cycle:
                            raise ValueError("Routing crossbar ports must be consistently either all ignore or not, panic in instruction ", instruction)
                    else:
                        routing_xbar_ports_if_prologued[src_operand['operand']] = invalid_cycle
                        
        # check 3: all the time_steps are aligned with the index_per_ii
        for operation in instruction['operations']:
            if operation['time_step'] % self.ii != instruction['index_per_ii']:
                print("Time step ", operation['time_step'], "ii", self.ii, " is not aligned with index per ii ", instruction['index_per_ii'])
                raise ValueError("Time step is not aligned with index per ii, panic in instruction ", instruction, " at operation ", operation)
                        
        return routing_xbar_ports_if_prologued

    
    
    def makePrologueFUPackets(self, timestep, prologue_count=1):
        # make prologue FU packet
        return self.IntraCgraPktType(0, self.id_, 
                                     payload = self.CgraPayloadType(self.CMD_CONFIG_PROLOGUE_FU_, ctrl_addr = self.CtrlAddrType(timestep % self.ii),
                                                                     data = self.DataType(prologue_count, 1)))
        
    def makePrologueRoutingCrossbarPackets(self, timestep, routing_xbar_idx, prologue_count=1):
        return self.IntraCgraPktType(0, self.id_, 
                                     payload = self.CgraPayloadType(self.CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_, ctrl_addr = self.CtrlAddrType(timestep % self.ii),
                                                                     ctrl = self.CtrlType(routing_xbar_outport = [self.TileInType(routing_xbar_idx)] + [self.TileInType(0)] * 7),
                                                                     data = self.DataType(prologue_count, 1)))
    def makePrologueFUCrossbarPackets(self, timestep, prologue_count=1):
        return self.IntraCgraPktType(0, self.id_, 
                                     payload = self.CgraPayloadType(self.CMD_CONFIG_PROLOGUE_FU_CROSSBAR_, ctrl_addr = self.CtrlAddrType(timestep % self.ii),
                                                                     ctrl = self.CtrlType(fu_xbar_outport = [self.FuOutType(0)] * 8),
                                                                     # WARN:by now, only support one result for each operation
                                                                     data = self.DataType(prologue_count, 1)))
    def makeTileSignals(self):
        consts = []
        all_signals = []
        all_instruction_signals = []
        prologue_signals = []
        has_addrs = []
        
        # build all the instruction signals and get all the const
        for instruction in self.instructions:
            print("================================================")
            print("Instruction: ", instruction)
             # do necessary sanitization
            prologued_ports = self.sanitize(instruction)
            
            # only when the take_up_fu_op exists and no prologue, then no prologue
            prologue_fu = False
            prologue_fu_cycles = 0
            has_take_up_fu_op = False
            non_take_up_fu_prologue_cycle_max = 0
            
            for operation in instruction['operations']:
                if operation['invalid_iterations'] > 1:
                    raise ValueError("Invalid iterations > 1 is not supported")
                elif operation['invalid_iterations'] == 1:
                    prologue_fu = True     
            
            for operation in instruction['operations']:
                if _is_take_up_fu_operation(operation):
                    has_take_up_fu_op = True
                    if operation['invalid_iterations'] == 0:
                        prologue_fu = False
                    else: # the prologue cycle depends on the comp instruction since only one take-up fu is allowed.
                        prologue_fu_cycles = operation['invalid_iterations'] # this should only be executed once.
                else:
                    non_take_up_fu_prologue_cycle_max = max(non_take_up_fu_prologue_cycle_max, operation['invalid_iterations'])
            
            if not has_take_up_fu_op: # pure move operations, the prologue should be the max of them
                prologue_fu_cycles = non_take_up_fu_prologue_cycle_max
                        
            
            # only non-taken prologue -> still need prologue FU
            # only taken prologue -> need prologue FU
            #  +--------------------+----------+--------------+
            #  | non-taken \ taken  | prologue | not prologue |
            #  +--------------------+----------+--------------+
            #  | prologue           |   yes    |    no        |
            #  | not prologue       |   yes    |    no        |
            #  +--------------------+----------+--------------+
                    
            if prologue_fu:
                prologue_signals.append(self.makePrologueFUPackets(instruction['index_per_ii'], prologue_fu_cycles))
                prologue_signals.append(self.makePrologueFUCrossbarPackets(instruction['index_per_ii'], prologue_fu_cycles))
                
            # add all routing crossbar prologues for all the operations (can not be op by op to avoid repetition)
            for port_name, cycles in prologued_ports.items():
                if cycles > 0:
                    routing_xbar_idx = direction_to_idx(port_name)
                    prologue_signals.append(self.makePrologueRoutingCrossbarPackets(instruction['index_per_ii'], routing_xbar_idx + 1, cycles))
                
            # add an addtional prologue packet for PHI_CONST / PHI_START operation
            for operation in instruction['operations']:
                if operation['opcode'] == 'PHI_CONST' or operation['opcode'] == "PHI_START":
                    # only src1 will be prologued once, and only if it is a port, it needs a routing crossbar prologue
                    if _type(operation['src_operands'][1]) == 'PORT':
                        routing_xbar_idx = direction_to_idx(operation['src_operands'][1]['operand'])
                        if operation['src_operands'][1]['operand'] in prologued_ports:
                            old_prologue_cycles = prologued_ports[operation['src_operands'][1]['operand']]
                            prologue_signals.append(self.makePrologueRoutingCrossbarPackets(operation['time_step'], routing_xbar_idx + 1, old_prologue_cycles + 1))
                        else:
                            prologue_signals.append(self.makePrologueRoutingCrossbarPackets(operation['time_step'], routing_xbar_idx + 1, 1))
            
            # mark this time slot is not empty
            has_addrs.append(instruction['index_per_ii'])
            
            instruction_signals = InstructionSignals(
                id_ = self.id_,
                operations = instruction['operations'],
                opcode_in_EIR = instruction['operations'][0]['opcode'], # transient TODO: make it general
                ctrl_addr = instruction['index_per_ii'],
                IntraCgraPktType = self.IntraCgraPktType,
                CgraPayloadType = self.CgraPayloadType,
                TileInType = self.TileInType,
                FuOutType = self.FuOutType,
                CMD_CONFIG_input = self.CMD_CONFIG_,
                CtrlType = self.CtrlType,
                FuInType = self.FuInType,
                B1Type = self.B1Type,
                B2Type = self.B2Type,
                RegIdxType = self.RegIdxType,
                CtrlAddrType = self.CtrlAddrType)
            all_instruction_signals.append(instruction_signals)
            
            const = instruction_signals.buildCtrlPkt()
            if const is not None:
                consts.extend(const)
        
        # make the const signals
        for idx, const_operand in enumerate(consts):
            const_pkt = self.IntraCgraPktType(0, self.id_, 
                                              payload = self.CgraPayloadType(self.CMD_CONST_,
                                                                             data = self.DataType(int(const_operand['operand'][1:] if const_operand['operand'].startswith('#') else const_operand['operand']), 1)))
            all_signals.append(const_pkt)
            
        # make the pre-configuration
        ii_pkt = self.IntraCgraPktType(0, self.id_, 
                                       payload = self.CgraPayloadType(self.CMD_CONFIG_COUNT_PER_ITER_,
                                                                      data = self.DataType(self.ii, 1)))
        all_signals.append(ii_pkt)
        loop_times_pkt = self.IntraCgraPktType(0, self.id_, 
                                               payload = self.CgraPayloadType(self.CMD_CONFIG_TOTAL_CTRL_COUNT_,
                                                                              data = self.DataType(self.loop_times, 1)))
        all_signals.append(loop_times_pkt)
        
        
        main_signals = []
        # make the main packets
        for instruction_signals in all_instruction_signals:
            pkt = instruction_signals.makeCtrlPkt()
            main_signals.append(pkt)
        
          
        # fill the non-existent timesteps with NAH packets

        filled_main_signals = []
        idx = 0
        for timestep in range(self.ii):
            if timestep not in has_addrs:
                NAH_SIGNAL = self.IntraCgraPktType(0, self.id_,
                            payload = self.CgraPayloadType(self.CMD_CONFIG_, ctrl_addr = self.CtrlAddrType(timestep),
                                                      ctrl = self.CtrlType(OPT_NAH,
                                                                      [self.FuInType(i) for i in range(1, 5)],
                                                                      [self.TileInType(0)] * 8,
                                                                      [self.FuOutType(0)] * 8)))  
                filled_main_signals.append(NAH_SIGNAL)
            else:
                filled_main_signals.append(main_signals[idx]) # WARN: generated signals must be in order
                idx += 1
        
        
        all_signals.extend(filled_main_signals)
            
        # make prologue packets
        # re-order the prologue packets 
        '''
        ordered_prologue_signals = []
        for pkt in prologue_signals:
            if pkt.cmd == self.CMD_CONFIG_PROLOGUE_FU_:
                ordered_prologue_signals.append(pkt)
        for pkt in prologue_signals:
            if pkt.cmd == self.CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_:
                ordered_prologue_signals.append(pkt)
        for pkt in prologue_signals:
            if pkt.cmd == self.CMD_CONFIG_PROLOGUE_FU_CROSSBAR_:
                ordered_prologue_signals.append(pkt)
                
        all_signals.extend(ordered_prologue_signals)
        '''
        all_signals.extend(prologue_signals)
        # make the launch packet
        launch_pkt = self.IntraCgraPktType(0, self.id_, 
                                           payload = self.CgraPayloadType(self.CMD_LAUNCH_))
        all_signals.append(launch_pkt)
        
        return all_signals
class ScriptFactory:
    FromFu = 0
    FromRouting = 1
    
    def __init__(self, 
                 path, 
                 CtrlType, 
                 IntraCgraPktType, 
                 CgraPayloadType, 
                 TileInType, 
                 FuOutType, 
                 CMD_CONFIG_input, 
                 FuInType, 
                 ii,
                 loop_times,
                 CMD_CONST_input,
                 CMD_CONFIG_COUNT_PER_ITER_input,
                 CMD_CONFIG_TOTAL_CTRL_COUNT_input,
                 CMD_CONFIG_PROLOGUE_FU_input,
                 CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input,
                 CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input,
                 CMD_LAUNCH_input,
                 DataType,
                 B1Type,
                 B2Type,
                 RegIdxType,
                 CtrlAddrType,
                 DataAddrType,
                 num_registers_per_reg_bank=None):
        # Allow overriding the default register cluster size.
        global REG_CLUSTER_SIZE
        if num_registers_per_reg_bank is not None:
            REG_CLUSTER_SIZE = int(num_registers_per_reg_bank)
        self.yaml_struct = yaml.load(open(path, 'r'), Loader=yaml.FullLoader)
        self.path = path
        self.CtrlType = CtrlType
        self.IntraCgraPktType = IntraCgraPktType
        self.CgraPayloadType = CgraPayloadType
        self.TileInType = TileInType
        self.FuOutType = FuOutType
        self.CMD_CONFIG_ = CMD_CONFIG_input
        self.FuInType = FuInType
        self.ii = ii
        self.loop_times = loop_times
        self.CMD_CONST_ = CMD_CONST_input
        self.CMD_CONFIG_COUNT_PER_ITER_ = CMD_CONFIG_COUNT_PER_ITER_input
        self.CMD_CONFIG_TOTAL_CTRL_COUNT_ = CMD_CONFIG_TOTAL_CTRL_COUNT_input
        self.CMD_CONFIG_PROLOGUE_FU_ = CMD_CONFIG_PROLOGUE_FU_input
        self.CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_ = CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input
        self.CMD_CONFIG_PROLOGUE_FU_CROSSBAR_ = CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input
        self.CMD_LAUNCH_ = CMD_LAUNCH_input
        self.DataType = DataType
        self.B1Type = B1Type
        self.B2Type = B2Type
        self.RegIdxType = RegIdxType
        self.CtrlAddrType = CtrlAddrType
        self.DataAddrType = DataAddrType
    
    def makeVectorCGRAPkts(self):
        
        pkts = {}
        cores = self.yaml_struct['array_config']['cores']
        
        
        for core in cores:
            x, y = core['column'], core['row']
            entry = core['entries'][0]
            instructions = entry['instructions']
            id_ = core['core_id']
            
            tile_signals = TileSignals(
                CtrlType = self.CtrlType,
                IntraCgraPktType = self.IntraCgraPktType,
                CgraPayloadType = self.CgraPayloadType,
                TileInType = self.TileInType,
                FuOutType = self.FuOutType,
                CMD_CONFIG_input = self.CMD_CONFIG_,
                FuInType = self.FuInType,
                id_ = id_,
                loop_times = self.loop_times, 
                ii = self.ii, 
                instructions = instructions,
                CMD_CONST_input = self.CMD_CONST_,
                CMD_CONFIG_COUNT_PER_ITER_input = self.CMD_CONFIG_COUNT_PER_ITER_,
                CMD_CONFIG_TOTAL_CTRL_COUNT_input = self.CMD_CONFIG_TOTAL_CTRL_COUNT_,
                CMD_CONFIG_PROLOGUE_FU_input = self.CMD_CONFIG_PROLOGUE_FU_,
                CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input = self.CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_,
                CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input = self.CMD_CONFIG_PROLOGUE_FU_CROSSBAR_,
                CMD_LAUNCH_input = self.CMD_LAUNCH_,
                DataType = self.DataType,
                B1Type = self.B1Type,
                B2Type = self.B2Type,
                RegIdxType = self.RegIdxType,
                CtrlAddrType = self.CtrlAddrType,
                DataAddrType = self.DataAddrType,
                )
            tile_signals = tile_signals.makeTileSignals()
            pkts[(x, y)] = tile_signals
            
        return pkts
    
from validation.test.dummy import *
    
if __name__ == "__main__":
    print("Test the Basic Functionality of the ScriptFactory")

    script_factory = ScriptFactory(
        path = "./validation/test/histogram.yaml",
        CtrlType = CtrlTypeDummy,
        IntraCgraPktType = IntraCgraPktTypeDummy,
        CgraPayloadType = CgraPayloadTypeDummy,
        TileInType = TileInTypeDummy,
        FuOutType = FuOutTypeDummy,
        CMD_CONFIG_input = CMD_CONFIG_Dummy(),
        FuInType = FuInTypeDummy,
        ii = 6,
        loop_times = 2,
        CMD_CONST_input = CMD_CONST_Dummy(),
        CMD_CONFIG_COUNT_PER_ITER_input = CMD_CONFIG_COUNT_PER_ITER_Dummy(),
        CMD_CONFIG_TOTAL_CTRL_COUNT_input = CMD_CONFIG_TOTAL_CTRL_COUNT_Dummy(),
        CMD_CONFIG_PROLOGUE_FU_input = CMD_CONFIG_PROLOGUE_FU_Dummy(),
        CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input = CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_Dummy(),
        CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input = CMD_CONFIG_PROLOGUE_FU_CROSSBAR_Dummy(),
        CMD_LAUNCH_input = CMD_LAUNCH_Dummy(),
        DataType = DataTypeDummy,
        B1Type = B1TypeDummy,
        B2Type = B2TypeDummy,
        RegIdxType = RegIdxTypeDummy,
        CtrlAddrType = CtrlAddrTypeDummy,
        DataAddrType = DataAddrTypeDummy,
    )
    
    pkts = script_factory.makeVectorCGRAPkts()
    for x, y in pkts:
        print(f"Tile ({x}, {y}):")
        for pkt in pkts[(x, y)]:
            print(pkt)
            print("--------------------------------")
    