"""
==========================================================================
script_generator.py
==========================================================================
A translator to translate yaml-formatted IR generated by compiler to the 
packets used in VectorCGRA

Author : Bohan Cui
  Date : Feb 25, 2026
"""

### Usage:
# 1. create factory instance with the types 
# (for the spec of the types, please refer to e.g. cgra/test/CgraRTL_fir_test.py)
# ```
# script_factory = ScriptFactory(
#     path = the_input_yaml,
#     CtrlType = your_CtrlType,
#     IntraCgraPktType = your_IntraCgraPktType,
#     CgraPayloadType = your_CgraPayloadType,
#     TileInType = your_TileInType,
#     FuOutType = your_FuOutType,
#     CMD_CONFIG_input = your_CMD_CONFIG_input,
#     FuInType = your_FuInType,
#     ii = your_ii,
#     loop_times = your_loop_times,
#     CMD_CONST_input = your_CMD_CONST_input,
#     CMD_CONFIG_COUNT_PER_ITER_input = your_CMD_CONFIG_COUNT_PER_ITER_input,
#     CMD_CONFIG_TOTAL_CTRL_COUNT_input = your_CMD_CONFIG_TOTAL_CTRL_COUNT_input,
#     CMD_CONFIG_PROLOGUE_FU_input = your_CMD_CONFIG_PROLOGUE_FU_input,
#     CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input = your_CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input,
#     CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input = your_CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input,
#     CMD_LAUNCH_input = your_CMD_LAUNCH_input,
#     DataType = your_DataType,
#     B1Type = your_B1Type,
#     B2Type = your_B2Type,
#     RegIdxType = your_RegIdxType,
#     CtrlAddrType = your_CtrlAddrType,
#     DataAddrType = your_DataAddrType,
# )
# ```
# 2. make the packets
# pkts = script_factory.makeVectorCGRAPkts()

import sys
import os
import yaml

# Add project root to path to allow imports from lib
# Get the absolute path of this file
_script_dir = os.path.dirname(os.path.abspath(__file__))
# Get the project root (parent of validation directory)
project_root = os.path.dirname(_script_dir)
# Normalize the path to handle any symlinks or relative path issues
project_root = os.path.normpath(os.path.abspath(project_root))

if project_root not in sys.path:
    sys.path.insert(0, project_root)

from lib.opt_type import *
from lib.util.common import *

# Global configuration for register cluster size (number of registers per cluster).
# This can be overridden by ScriptFactory initialization.
REG_CLUSTER_SIZE = 8

yaml_to_VectorCGRA_map = {
    "CONSTANT": OPT_CONST, # ?
    "ADD": OPT_ADD,
    "MUL": OPT_MUL,
    "SUB": OPT_SUB,
    "DIV": OPT_DIV,
    "REM": OPT_REM,
    "FADD": OPT_FADD,
    "FSUB": OPT_FSUB,
    "FMUL": OPT_FMUL,
    "FDIV": None, # ?
    "OR": OPT_OR,
    "AND": OPT_AND,
    "XOR": OPT_XOR,
    "NOT": OPT_NOT,
    "ICMP": None, # ?
    "EQ": OPT_EQ,
    "LT": OPT_LT,
    "GT": OPT_GT,
    "LTE": OPT_LTE,
    "GTE": OPT_GTE,
    "FCMP": None, # ?
    "SEL": OPT_SEL,
    "CAST": None, # ?
    "SEXT": OPT_PAS, # no sext, just a fake one.
    "ZEXT": OPT_PAS, # no zext, just a fake one.
    "SHL": OPT_LLS,
    "VFMUL": None, # ?
    "FADD_FADD": None, #?
    "FMUL_FADD": None, #?
    "DATA_MOV": None, #?
    "CTRL_MOV": OPT_PAS,
    "RESERVE": None, #?
    "GRANT_PREDICATE": OPT_GRT_PRED,
    "GRANT_ALWAYS": None, #?
    "GRANT_ONCE": OPT_GRT_ONCE, #?
    "PHI": OPT_PHI,
    "PHI_START": OPT_PHI_START,
    "LOOP_CONTROL": None, #?
    "PHI_CONST": OPT_PHI_CONST, 
    
    "RETURN": OPT_RET,
    "RETURN_VOID": OPT_RET_VOID,
    "LDD": OPT_LD,
    "LOAD": OPT_LD,
    "STORE": OPT_STR,
    
    "NE": OPT_NE,
    "MUL_ADD": OPT_MUL_ADD,
    "DATA_MOV": OPT_PAS
    
}

yaml_to_VectorCGRA_map_const = {
    "EQ": OPT_EQ_CONST,
    "NE": OPT_NE_CONST,
    "ADD": OPT_ADD_CONST,
    "GEP": OPT_ADD_CONST,
    "MUL_ADD": OPT_MUL_CONST_ADD,
    "MUL": OPT_MUL_CONST,
}



def _type(Operand):
    impl = Operand['operand']
    if impl[0] == "$":
        return 'REG'
    elif impl.upper() in ['NORTH', 'SOUTH', 'WEST', 'EAST', 'SOUTHEAST', 'SOUTHWEST', 'NORTHWEST', 'NORTHEAST']:
        return 'PORT'
    else:
        return 'IMM'

def _is_take_up_fu_operation(operation):
    if operation['opcode'] == 'MOV' or operation['opcode'] == 'DATA_MOV' or operation['opcode'] == 'CTRL_MOV':
        if len(operation['src_operands']) != 1:
            raise ValueError("MOV operation must have exactly one source operand")
        elif _type(operation['src_operands'][0]) == 'REG':
            return True
        else:
            return False
    else:
        return True

def _prologue_count_of(operation, default=1):
    count = operation.get('invalid_iterations', default)
    if count is None:
        count = default
    count = int(count)
    if count < 0:
        raise ValueError(f"invalid_iterations must be non-negative, got {count} in operation {operation}")
    return count
    
def _reg_cluster_no_of(operand): # start from 1
    impl = operand['operand']
    if impl[0] == "$":
        return int(impl[1:]) // REG_CLUSTER_SIZE + 1
    else:
        raise ValueError("Operand is not a register")

def _reg_cluster_intra_index_of(operand):
    impl = operand['operand']
    if impl[0] == "$":
        return int(impl[1:]) % REG_CLUSTER_SIZE
    else:
        raise ValueError("Operand is not a register")

FROM_NOWHERE = 0
FROM_PORT = 1
FROM_FU = 2
FROM_CONSTANT_QUEUE = 3 # not used by now

OPR_FROM_PORT = 0
OPR_FROM_REGISTER = 1

PORT_CODE = {
    "NORTH": PORT_NORTH,
    "SOUTH": PORT_SOUTH,
    "WEST": PORT_WEST,
    "EAST": PORT_EAST,
    "NORTHWEST": PORT_NORTHWEST,
    "NORTHEAST": PORT_NORTHEAST,
    "SOUTHEAST": PORT_SOUTHEAST,
    "SOUTHWEST": PORT_SOUTHWEST,
}

PORT_OUT_INDEX = {
    "NORTH": PORT_INDEX_NORTH,
    "SOUTH": PORT_INDEX_SOUTH,
    "WEST": PORT_INDEX_WEST,
    "EAST": PORT_INDEX_EAST,
    "NORTHWEST": PORT_INDEX_NORTHWEST,
    "NORTHEAST": PORT_INDEX_NORTHEAST,
    "SOUTHEAST": PORT_INDEX_SOUTHEAST,
    "SOUTHWEST": PORT_INDEX_SOUTHWEST,
}

class InstructionSignals:
    # to make signal of single instruction
    def __init__(self, 
                 # input
                 id_,
                 operations,
                 opcode_in_EIR,
                 ctrl_addr,
                 # types
                 IntraCgraPktType, 
                 CgraPayloadType, 
                 TileInType, 
                 FuOutType, 
                 CMD_CONFIG_input, 
                 CtrlType,
                 FuInType,
                 B1Type,
                 B2Type,
                 RegIdxType,
                 CtrlAddrType,
                 num_tile_inports=4,
                 num_tile_outports=4,
                 num_fu_inports=4):
        # types
        self.IntraCgraPktType = IntraCgraPktType
        self.CgraPayloadType = CgraPayloadType
        self.TileInType = TileInType
        self.FuOutType = FuOutType
        self.CMD_CONFIG_ = CMD_CONFIG_input
        self.CtrlType = CtrlType
        self.FuInType = FuInType
        self.B1Type = B1Type
        self.B2Type = B2Type
        self.RegIdxType = RegIdxType
        self.CtrlAddrType = CtrlAddrType
        self.num_tile_inports = num_tile_inports
        self.num_tile_outports = num_tile_outports
        self.num_fu_inports = num_fu_inports
        self.num_routing_outports = num_tile_outports + num_fu_inports
        
        # inputs
        self.id_ = id_
        self.operations = operations
        self.OpCode = opcode_in_EIR
        self.ctrl_addr = ctrl_addr
        
        # States
        self.TileInParams = [-1 for _ in range(self.num_routing_outports)]
        self.FuOutParams = [-1 for _ in range(self.num_routing_outports)]
        self.read_from_reg = [-1 for _ in range(self.num_fu_inports)]
        self.read_from_reg_idx = [-1 for _ in range(self.num_fu_inports)]
        self.write_to_reg = [-1 for _ in range(self.num_fu_inports)]
        self.write_to_reg_idx = [-1 for _ in range(self.num_fu_inports)]
        self.shuffle_fu_operand_input_index = [-1 for _ in range(self.num_fu_inports)]

        
    def buildCtrlPkt(self) -> list: # return the const needed to put into the const queue
        # you must call buildCtrlPkt before makeCtrlPkt, and for a Tile's signal, you must call buildCtrlPkt in order.
        try:
            take_up_fu_operation_idx = -1
            for idx, operation in enumerate(self.operations):
                if _is_take_up_fu_operation(operation):
                    if take_up_fu_operation_idx != -1:
                        raise ValueError("Only one take up fu operation is allowed")
                    take_up_fu_operation_idx = idx
            
            # TODO: fix logic here
                  
            take_up_fu_operation = self.operations[take_up_fu_operation_idx] if take_up_fu_operation_idx != -1 else None
            has_const = False
            # if has src_operands, check if has const
            src_operands = take_up_fu_operation.get('src_operands', []) if take_up_fu_operation is not None else []
            for src_operand in src_operands:
                if _type(src_operand) == 'IMM':
                    has_const = True
                    break 
                
            if take_up_fu_operation is not None and (take_up_fu_operation['opcode'] == 'PHI_CONST' or take_up_fu_operation['opcode'] == 'CONSTANT' or take_up_fu_operation['opcode'] == 'GRANT_ONCE'):
                has_const = False # PHI_CONST and CONSTANT are special.
            
            if take_up_fu_operation is None:
                self.opCode = OPT_NAH
            elif has_const:
                self.opCode = yaml_to_VectorCGRA_map_const[take_up_fu_operation['opcode']]
            else:
                self.opCode = yaml_to_VectorCGRA_map[take_up_fu_operation['opcode']]

            const_operands = []

            for operation in self.operations: # for each operation in the instruction
                
                print("Working on operation: ", operation)
                
                operation_opcode = operation['opcode']
                try:
                    src_operands = operation['src_operands']
                except Exception as e:
                    src_operands = []
                try:
                    dst_operands = operation['dst_operands']
                except Exception as e:
                    dst_operands = []
                grant_once_const_source = (
                    operation_opcode == 'GRANT_ONCE' and
                    len(src_operands) == 1 and
                    _type(src_operands[0]) == 'IMM'
                )

                if not _is_take_up_fu_operation(operation):
                    if len(src_operands) != 1 or _type(src_operands[0]) != 'PORT':
                        raise ValueError(f"Non-FU DATA_MOV only supports one PORT source, got {operation}")
                    port_in_xbar_idx = PORT_CODE[src_operands[0]['operand']]
                    for dst_operand in dst_operands:
                        if _type(dst_operand) == 'REG':
                            cluster_no = _reg_cluster_no_of(dst_operand)
                            intra_index = _reg_cluster_intra_index_of(dst_operand)
                            if cluster_no < 1 or cluster_no > len(self.write_to_reg_idx):
                                raise ValueError(f"Register cluster number {cluster_no} is out of range. Valid range is 1 to {len(self.write_to_reg_idx)} for register {dst_operand['operand']} in operation {operation}")
                            if intra_index < 0 or intra_index >= REG_CLUSTER_SIZE:
                                raise ValueError(f"Register intra index {intra_index} is out of range. Valid range is 0 to {REG_CLUSTER_SIZE-1} for register {dst_operand['operand']} in operation {operation}")
                            if self.write_to_reg_idx[cluster_no - 1] != -1 and self.write_to_reg_idx[cluster_no - 1] != intra_index:
                                raise ValueError(f"Collision when writing to register in write_to_reg_idx, when translate the operation {operation} to VectorCGRA")
                            self.write_to_reg[cluster_no - 1] = FROM_PORT
                            self.write_to_reg_idx[cluster_no - 1] = intra_index
                            routing_out_idx = self.num_tile_outports + cluster_no - 1
                            if self.TileInParams[routing_out_idx] != -1 and self.TileInParams[routing_out_idx] != port_in_xbar_idx:
                                raise ValueError(f"Collision in routing DATA_MOV to register, when translate the operation {operation} to VectorCGRA")
                            self.TileInParams[routing_out_idx] = port_in_xbar_idx
                        elif _type(dst_operand) == 'PORT':
                            port_out_xbar_idx = PORT_OUT_INDEX[dst_operand['operand']]
                            if self.TileInParams[port_out_xbar_idx] != -1 and self.TileInParams[port_out_xbar_idx] != port_in_xbar_idx:
                                raise ValueError(f"Collision in routing DATA_MOV to port, when translate the operation {operation} to VectorCGRA")
                            self.TileInParams[port_out_xbar_idx] = port_in_xbar_idx
                        else:
                            raise ValueError(f"Unsupported type of DATA_MOV dst operand {dst_operand}, when translate the operation {operation} to VectorCGRA")
                    continue
                
                # find all the const
                normalized_src_operands = []
                for src_operand in src_operands:
                    if _type(src_operand) == 'IMM':
                        const_operands.append(src_operand)
                        # delete it from the src_operands since it is implicit in vectorCGRA
                    else:
                        normalized_src_operands.append(src_operand)
                src_operands = normalized_src_operands
                if grant_once_const_source:
                    if self.shuffle_fu_operand_input_index[0] != -1:
                        raise ValueError(f"Collision when assigning GRANT_ONCE const source, when translate the operation {operation} to VectorCGRA")
                    self.shuffle_fu_operand_input_index[0] = 0

                reserved_reg_lanes = set()
                for src_operand in src_operands:
                    if _type(src_operand) == 'REG':
                        cluster_no = _reg_cluster_no_of(src_operand)
                        if cluster_no < 1 or cluster_no > len(self.read_from_reg_idx):
                            raise ValueError(f"Register cluster number {cluster_no} is out of range. Valid range is 1 to {len(self.read_from_reg_idx)} for register {src_operand['operand']} in operation {operation}")
                        reserved_reg_lanes.add(cluster_no - 1)
                
                for index, src_operand in enumerate(src_operands):
                    if _type(src_operand) == 'REG':
                        print(f">>> index {index} is REG")
                        cluster_no = _reg_cluster_no_of(src_operand)
                        intra_index = _reg_cluster_intra_index_of(src_operand)
                        # Check if cluster_no is within valid range (1 to num_fu_inports)
                        if cluster_no < 1 or cluster_no > len(self.read_from_reg_idx):
                            raise ValueError(f"Register cluster number {cluster_no} is out of range. Valid range is 1 to {len(self.read_from_reg_idx)} for register {src_operand['operand']} in operation {operation}")
                        # Check if intra_index is within valid range (0 to REG_CLUSTER_SIZE-1)
                        if intra_index < 0 or intra_index >= REG_CLUSTER_SIZE:
                            raise ValueError(f"Register intra index {intra_index} is out of range. Valid range is 0 to {REG_CLUSTER_SIZE-1} for register {src_operand['operand']} in operation {operation}")
                        if self.read_from_reg_idx[cluster_no - 1] != -1 and self.read_from_reg_idx[cluster_no - 1] != intra_index:
                            raise ValueError(f"Collision when reading from register in read_from_reg_idx, when translate the operation {operation} to VectorCGRA")
                        if self.read_from_reg[cluster_no - 1] != -1 and self.read_from_reg[cluster_no - 1] != OPR_FROM_REGISTER:
                            raise ValueError(f"Collision between register and port source lanes, when translate the operation {operation} to VectorCGRA")
                        self.read_from_reg[cluster_no - 1] = OPR_FROM_REGISTER
                        self.read_from_reg_idx[cluster_no - 1] = intra_index
                        if self.shuffle_fu_operand_input_index[index] != -1:
                            raise ValueError(f"Collision when reading from register in shuffle_fu_operand_input_index, when translate the operation {operation} to VectorCGRA")
                        self.shuffle_fu_operand_input_index[index] = cluster_no # shuffle the data to the correct inport of the FU from the register
                    if _type(src_operand) == 'PORT':
                        port_in_xbar_idx = PORT_CODE[src_operand['operand']]
                            
                        # find an available lane
                        lane = -1
                        for i in range(self.num_fu_inports):
                            if self.read_from_reg[i] == -1 and i not in reserved_reg_lanes: # if not set the selection, then it could be available
                                lane = i
                                break
                        if lane == -1:
                            raise ValueError(f"No available lane found when reading from port {src_operand} in TileInParams, when translate the operation {operation} to VectorCGRA")
                        if self.TileInParams[lane + self.num_tile_outports] != -1:
                            raise ValueError(f"Collision in reading from port in TileInParams, when translate the operation {operation} to VectorCGRA")
                        self.TileInParams[lane + self.num_tile_outports] = port_in_xbar_idx
                        self.read_from_reg[lane] = OPR_FROM_PORT
                        # shuffle to the given fu input index
                        if self.shuffle_fu_operand_input_index[index] != -1:
                            raise ValueError(f"Collision when reading from port in shuffle_fu_operand_input_index, when translate the operation {operation} to VectorCGRA")
                        self.shuffle_fu_operand_input_index[index] = lane + 1
                        
                    if _type(src_operand) == 'IMM':
                        raise NotImplementedError("IMM src operand is not supported yet")
                    
                for index, dst_operand in enumerate(dst_operands):
                    if _type(dst_operand) == 'REG':
                        cluster_no = _reg_cluster_no_of(dst_operand)
                        intra_index = _reg_cluster_intra_index_of(dst_operand)
                        # Check if cluster_no is within valid range (1 to num_fu_inports)
                        if cluster_no < 1 or cluster_no > len(self.write_to_reg_idx):
                            raise ValueError(f"Register cluster number {cluster_no} is out of range. Valid range is 1 to {len(self.write_to_reg_idx)} for register {dst_operand['operand']} in operation {operation}")
                        # Check if intra_index is within valid range (0 to REG_CLUSTER_SIZE-1)
                        if intra_index < 0 or intra_index >= REG_CLUSTER_SIZE:
                            raise ValueError(f"Register intra index {intra_index} is out of range. Valid range is 0 to {REG_CLUSTER_SIZE-1} for register {dst_operand['operand']} in operation {operation}")
                        if self.write_to_reg_idx[cluster_no - 1] != -1 and self.write_to_reg_idx[cluster_no - 1] != intra_index:
                            raise ValueError(f"Collision when writing to register in write_to_reg_idx, when translate the operation {operation} to VectorCGRA")
                        self.write_to_reg[cluster_no - 1] = FROM_FU
                        self.write_to_reg_idx[cluster_no - 1] = intra_index
                        fu_out_idx = self.num_tile_outports + cluster_no - 1
                        if self.FuOutParams[fu_out_idx] != -1:
                            raise ValueError(f"Collision in writing result to register, when translate the operation {operation} to VectorCGRA")
                        self.FuOutParams[fu_out_idx] = 1
                    elif _type(dst_operand) == 'PORT':
                        port_out_xbar_idx = PORT_OUT_INDEX[dst_operand['operand']]
                        if self.FuOutParams[port_out_xbar_idx] != -1:
                            raise ValueError(f"Collision in writing to port {dst_operand} in FuOutParams, when translate the operation {operation} to VectorCGRA")
                        print(f">>> FuOutParams[{port_out_xbar_idx}] = {index + 1}")
                        self.FuOutParams[port_out_xbar_idx] = 1 # we do not support multiple results 
                    else:
                        raise ValueError(f"Unsupported type of dst operand {dst_operand}, when translate the operation {operation} to VectorCGRA")
        
        except Exception as e:
            print(f"Error in making ctrl pkt: {e}")
            raise e
            return None
        return const_operands
        
    def makeCtrlPkt(self):
        # make fu_in_code
        for idx, fu_in_code in enumerate(self.shuffle_fu_operand_input_index):
            if fu_in_code == -1:
                self.shuffle_fu_operand_input_index[idx] = idx + 1 # 0 or idle inport of ALU?
        fu_in_code_made = [self.FuInType(x) for x in self.shuffle_fu_operand_input_index] # is it correct?
        
        # make TileIn
        for idx, tile_in_param in enumerate(self.TileInParams):
            if tile_in_param == -1:
                self.TileInParams[idx] = 0
        TileIn_made = [self.TileInType(x) for x in self.TileInParams]
        for idx, fu_out_param in enumerate(self.FuOutParams):
            if fu_out_param == -1:
                self.FuOutParams[idx] = 0
        FuOut_made = [self.FuOutType(x) for x in self.FuOutParams]
        
        # made write reg from code
        for idx, write_to_reg in enumerate(self.write_to_reg):
            if write_to_reg == -1:
                self.write_to_reg[idx] = FROM_NOWHERE
        write_reg_from_made = [self.B2Type(x) for x in self.write_to_reg]
        
        for idx, write_to_reg_idx in enumerate(self.write_to_reg_idx):
            if write_to_reg_idx == -1:
                self.write_to_reg_idx[idx] = 0
        write_reg_idx_made = [self.RegIdxType(x) for x in self.write_to_reg_idx]
        
        # make read reg from code
        for idx, read_from_reg in enumerate(self.read_from_reg):
            if read_from_reg == -1:
                self.read_from_reg[idx] = OPR_FROM_PORT

        read_reg_from_made = [self.B1Type(x) for x in self.read_from_reg]
        
        for idx, read_from_reg_idx in enumerate(self.read_from_reg_idx):
            if read_from_reg_idx == -1:
                self.read_from_reg_idx[idx] = 0
        read_reg_idx_made = [self.RegIdxType(x) for x in self.read_from_reg_idx]
        
        # make FuOut
        # CtrlType requires: operation, fu_in, routing_xbar_outport, fu_xbar_outport,
        #                    vector_factor_power, is_last_ctrl, write_reg_from, write_reg_idx,
        #                    read_reg_from, read_reg_idx
        # Use keyword arguments for optional fields to avoid parameter order issues
        pkt = self.IntraCgraPktType(0, self.id_, 
                                    payload = self.CgraPayloadType(self.CMD_CONFIG_, 
                                                                    ctrl_addr = self.CtrlAddrType(self.ctrl_addr), 
                                                                    ctrl = self.CtrlType(self.opCode,
                                                                                        fu_in_code_made,
                                                                                        TileIn_made,
                                                                                        FuOut_made,
                                                                                        write_reg_from = write_reg_from_made,
                                                                                        write_reg_idx = write_reg_idx_made,
                                                                                        read_reg_from = read_reg_from_made,
                                                                                        read_reg_idx = read_reg_idx_made,
                                                                                        )))
        return pkt

class TileSignals:
    def __init__(self,
                CtrlType, 
                IntraCgraPktType, 
                CgraPayloadType, 
                TileInType, 
                FuOutType, 
                CMD_CONFIG_input, 
                FuInType, 
                id_, 
                loop_times,
                ii,
                instructions,
                CMD_CONST_input,
                CMD_CONFIG_COUNT_PER_ITER_input,
                CMD_CONFIG_TOTAL_CTRL_COUNT_input,
                CMD_CONFIG_PROLOGUE_FU_input,
                CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input,
                CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input,
                CMD_LAUNCH_input,
                DataType,
                B1Type,
                B2Type,
                RegIdxType,
                CtrlAddrType,
                DataAddrType,
                num_tile_inports=4,
                num_tile_outports=4,
                num_fu_inports=4):
        self.CtrlType = CtrlType
        self.IntraCgraPktType = IntraCgraPktType
        self.CgraPayloadType = CgraPayloadType
        self.TileInType = TileInType
        self.FuOutType = FuOutType
        self.CMD_CONFIG_ = CMD_CONFIG_input
        self.FuInType = FuInType
        self.id_ = id_
        self.instructions = instructions
        self.loop_times = loop_times
        self.ii = ii
        self.B1Type = B1Type
        self.B2Type = B2Type
        self.RegIdxType = RegIdxType
        self.DataType = DataType
        self.CtrlAddrType = CtrlAddrType
        self.DataAddrType = DataAddrType
        self.num_tile_inports = num_tile_inports
        self.num_tile_outports = num_tile_outports
        self.num_fu_inports = num_fu_inports
        self.num_routing_outports = num_tile_outports + num_fu_inports
        # constants
        self.CMD_CONST_ = CMD_CONST_input
        self.CMD_CONFIG_COUNT_PER_ITER_ = CMD_CONFIG_COUNT_PER_ITER_input
        self.CMD_CONFIG_TOTAL_CTRL_COUNT_ = CMD_CONFIG_TOTAL_CTRL_COUNT_input
        
        self.CMD_CONFIG_PROLOGUE_FU_ = CMD_CONFIG_PROLOGUE_FU_input
        self.CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_ = CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input
        self.CMD_CONFIG_PROLOGUE_FU_CROSSBAR_ = CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input
        
        self.CMD_LAUNCH_ = CMD_LAUNCH_input
        
        
    def makeProloguePackets(self, instruction):
        print(f"Making prologue packets for instruction {instruction}")
        pkts = []
        fu_prologue_count = 0
        routing_prologue_counts = {}
        fu_crossbar_prologue_counts = {}
        default_prologue_count = 1 if instruction['timestep'] >= self.ii else 0
        take_up_fu_operation_idx = -1
        for idx, operation in enumerate(instruction['operations']):
            if _is_take_up_fu_operation(operation):
                if take_up_fu_operation_idx != -1:
                    raise ValueError("Only one take up fu operation is allowed")
                take_up_fu_operation_idx = idx
        take_up_fu_operation = None  
        if take_up_fu_operation_idx != -1:
            take_up_fu_operation = instruction['operations'][take_up_fu_operation_idx]
            # TODO: fix the logic for only having non-take up fu operation

        for operation in instruction['operations']:
            prologue_count = _prologue_count_of(operation, default_prologue_count)
            try:
                src_operands = operation['src_operands']
            except Exception as e:
                src_operands = []
            try:
                dst_operands = operation['dst_operands']
            except Exception as e:
                dst_operands = []

            if operation['opcode'] == 'PHI_START':
                for src_operand in src_operands[1:]:
                    if _type(src_operand) == 'PORT':
                        routing_xbar_idx = PORT_CODE[src_operand['operand']]
                        routing_prologue_counts[routing_xbar_idx] = max(
                            routing_prologue_counts.get(routing_xbar_idx, 0),
                            prologue_count + 1,
                        )
            if prologue_count == 0:
                continue

            if _is_take_up_fu_operation(operation):
                fu_prologue_count = max(fu_prologue_count, prologue_count)
                for src_operand in src_operands:
                    if _type(src_operand) == 'PORT':
                        print(f"src_operand is PORT, add Prologue. {src_operand}")
                        routing_xbar_idx = PORT_CODE[src_operand['operand']]
                        routing_prologue_counts[routing_xbar_idx] = max(
                            routing_prologue_counts.get(routing_xbar_idx, 0),
                            prologue_count,
                        )
                for dst_operand in dst_operands:
                    if _type(dst_operand) == 'REG' or _type(dst_operand) == 'PORT':
                        fu_crossbar_prologue_counts[1] = max(
                            fu_crossbar_prologue_counts.get(1, 0),
                            prologue_count,
                        )
            else:
                for src_operand in src_operands:
                    if _type(src_operand) == 'PORT':
                        routing_xbar_idx = PORT_CODE[src_operand['operand']]
                        routing_prologue_counts[routing_xbar_idx] = max(
                            routing_prologue_counts.get(routing_xbar_idx, 0),
                            prologue_count,
                        )

        if fu_prologue_count > 0:
            pkts.append(self.makePrologueFUPackets(instruction, fu_prologue_count))
        for routing_xbar_idx, prologue_count in routing_prologue_counts.items():
            pkts.append(self.makePrologueRoutingCrossbarPackets(instruction, routing_xbar_idx, prologue_count))
        for fu_xbar_idx, prologue_count in fu_crossbar_prologue_counts.items():
            pkts.append(self.makePrologueFUCrossbarPackets(instruction, fu_xbar_idx, prologue_count))
        return pkts
    
    def makePhiConstProloguePackets(self, instruction):
        print(f"Making phi const prologue packets for instruction {instruction}")
        for operation in instruction['operations']:
            if operation['opcode'] == 'PHI_CONST':
                phi_const_operation = operation
                break
        if phi_const_operation is None:
            raise ValueError("No PHI_CONST operation found")
        try:
            src_operands = phi_const_operation['src_operands']
        except Exception as e:
            src_operands = []
            
        pkts = []
        prologue_count = _prologue_count_of(phi_const_operation, 1)
        if prologue_count == 0:
            return pkts
        
        for src_operand in src_operands:
            if _type(src_operand) == 'PORT':
                routing_xbar_idx = PORT_CODE[src_operand['operand']]
                pkts.append(self.makePrologueRoutingCrossbarPackets(instruction, routing_xbar_idx, prologue_count))
                
        print(f"Phi const prologue packets: {pkts}")
        return pkts
    
    
    def makePrologueFUPackets(self, instruction, prologue_count=1):
        return self.IntraCgraPktType(0, self.id_, 
                                     payload = self.CgraPayloadType(self.CMD_CONFIG_PROLOGUE_FU_, ctrl_addr = self.CtrlAddrType(instruction.get('ctrl_addr', instruction['timestep'] % self.ii)),
                                                                     data = self.DataType(prologue_count, 1)))
    def makePrologueRoutingCrossbarPackets(self, instruction, routing_xbar_idx, prologue_count=1):
        return self.IntraCgraPktType(0, self.id_, 
                                     payload = self.CgraPayloadType(self.CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_, ctrl_addr = self.CtrlAddrType(instruction.get('ctrl_addr', instruction['timestep'] % self.ii)),
                                                                     ctrl = self.CtrlType(routing_xbar_outport = [self.TileInType(routing_xbar_idx)] + [self.TileInType(0)] * (self.num_routing_outports - 1)),
                                                                     data = self.DataType(prologue_count, 1)))
    def makePrologueFUCrossbarPackets(self, instruction, fu_xbar_idx=1, prologue_count=1):
        return self.IntraCgraPktType(0, self.id_, 
                                     payload = self.CgraPayloadType(self.CMD_CONFIG_PROLOGUE_FU_CROSSBAR_, ctrl_addr = self.CtrlAddrType(instruction.get('ctrl_addr', instruction['timestep'] % self.ii)),
                                                                     ctrl = self.CtrlType(fu_xbar_outport = [self.FuOutType(fu_xbar_idx)] + [self.FuOutType(0)] * (self.num_routing_outports - 1)),
                                                                     data = self.DataType(prologue_count, 1)))
    def makeTileSignals(self):
        consts = []
        all_signals = []
        all_instruction_signals = []
        prologue_signals = []
        has_addrs = []
        
        # build all the instruction signals and get all the const
        for instruction in self.instructions:
            prologue_signals.extend(self.makeProloguePackets(instruction))
            
            has_phi_const = False # cope with special PHI_CONST operation
            for operation in instruction['operations']:
                if operation['opcode'] == 'PHI_CONST':
                    has_phi_const = True
                    break
            if has_phi_const:
                prologue_signals.extend(self.makePhiConstProloguePackets(instruction))
                
            has_addrs.append(instruction.get('ctrl_addr', instruction['timestep'] % self.ii))
            
            instruction_signals = InstructionSignals(
                id_ = self.id_,
                operations = instruction['operations'],
                opcode_in_EIR = instruction['operations'][0]['opcode'], # transient TODO: make it general
                ctrl_addr = instruction.get('ctrl_addr', instruction['timestep'] % self.ii),
                IntraCgraPktType = self.IntraCgraPktType,
                CgraPayloadType = self.CgraPayloadType,
                TileInType = self.TileInType,
                FuOutType = self.FuOutType,
                CMD_CONFIG_input = self.CMD_CONFIG_,
                CtrlType = self.CtrlType,
                FuInType = self.FuInType,
                B1Type = self.B1Type,
                B2Type = self.B2Type,
                RegIdxType = self.RegIdxType,
                CtrlAddrType = self.CtrlAddrType,
                num_tile_inports = self.num_tile_inports,
                num_tile_outports = self.num_tile_outports,
                num_fu_inports = self.num_fu_inports)
            all_instruction_signals.append(instruction_signals)
            
            const = instruction_signals.buildCtrlPkt()
            if const is not None:
                consts.extend(const)
        
        # make the const signals
        for idx, const_operand in enumerate(consts):
            const_pkt = self.IntraCgraPktType(0, self.id_, 
                                              payload = self.CgraPayloadType(self.CMD_CONST_,
                                                                             data = self.DataType(int(const_operand['operand'][1:] if const_operand['operand'].startswith('#') else const_operand['operand']), 1)))
            all_signals.append(const_pkt)
            
        # make the pre-configuration
        ii_pkt = self.IntraCgraPktType(0, self.id_, 
                                       payload = self.CgraPayloadType(self.CMD_CONFIG_COUNT_PER_ITER_,
                                                                      data = self.DataType(self.ii, 1)))
        all_signals.append(ii_pkt)
        loop_times_pkt = self.IntraCgraPktType(0, self.id_, 
                                               payload = self.CgraPayloadType(self.CMD_CONFIG_TOTAL_CTRL_COUNT_,
                                                                              data = self.DataType(self.loop_times, 1)))
        all_signals.append(loop_times_pkt)
        
        
        main_signals_by_addr = {}
        # make the main packets
        for instruction_signals in all_instruction_signals:
            pkt = instruction_signals.makeCtrlPkt()
            addr = int(pkt.payload.ctrl_addr)
            if addr in main_signals_by_addr:
                raise ValueError(f"Duplicate control packet for ctrl_addr {addr} in tile {self.id_}")
            main_signals_by_addr[addr] = pkt
        
          
        # fill the non-existent timesteps with NAH packets

        filled_main_signals = []
        for timestep in range(self.ii):
            if timestep not in has_addrs:
                NAH_SIGNAL = self.IntraCgraPktType(0, self.id_,
                            payload = self.CgraPayloadType(self.CMD_CONFIG_, ctrl_addr = self.CtrlAddrType(timestep),
                                                      ctrl = self.CtrlType(OPT_NAH,
                                                                      [self.FuInType(i) for i in range(1, self.num_fu_inports + 1)],
                                                                      [self.TileInType(0)] * self.num_routing_outports,
                                                                      [self.FuOutType(0)] * self.num_routing_outports)))  
                filled_main_signals.append(NAH_SIGNAL)
            else:
                filled_main_signals.append(main_signals_by_addr[timestep])
        
        
        all_signals.extend(filled_main_signals)
            
        # make prologue packets
        # re-order the prologue packets 
        '''
        ordered_prologue_signals = []
        for pkt in prologue_signals:
            if pkt.cmd == self.CMD_CONFIG_PROLOGUE_FU_:
                ordered_prologue_signals.append(pkt)
        for pkt in prologue_signals:
            if pkt.cmd == self.CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_:
                ordered_prologue_signals.append(pkt)
        for pkt in prologue_signals:
            if pkt.cmd == self.CMD_CONFIG_PROLOGUE_FU_CROSSBAR_:
                ordered_prologue_signals.append(pkt)
                
        all_signals.extend(ordered_prologue_signals)
        '''
        all_signals.extend(prologue_signals)
        # make the launch packet
        launch_pkt = self.IntraCgraPktType(0, self.id_, 
                                           payload = self.CgraPayloadType(
                                               self.CMD_LAUNCH_,
                                               ctrl = self.CtrlType(OPT_NAH)))
        all_signals.append(launch_pkt)
        
        return all_signals
class ScriptFactory:
    FromFu = 0
    FromRouting = 1
    
    def __init__(self, 
                 path, 
                 CtrlType, 
                 IntraCgraPktType, 
                 CgraPayloadType, 
                 TileInType, 
                 FuOutType, 
                 CMD_CONFIG_input, 
                 FuInType, 
                 ii,
                 loop_times,
                 CMD_CONST_input,
                 CMD_CONFIG_COUNT_PER_ITER_input,
                 CMD_CONFIG_TOTAL_CTRL_COUNT_input,
                 CMD_CONFIG_PROLOGUE_FU_input,
                 CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input,
                 CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input,
                 CMD_LAUNCH_input,
                 DataType,
                 B1Type,
                 B2Type,
                 RegIdxType,
                 CtrlAddrType,
                 DataAddrType,
                 num_registers_per_reg_bank=None,
                 num_tile_inports=4,
                 num_tile_outports=4,
                 num_fu_inports=4):
        # Allow overriding the default register cluster size.
        global REG_CLUSTER_SIZE
        if num_registers_per_reg_bank is not None:
            REG_CLUSTER_SIZE = int(num_registers_per_reg_bank)
        self.yaml_struct = yaml.load(open(path, 'r'), Loader=yaml.FullLoader)
        self.path = path
        self.CtrlType = CtrlType
        self.IntraCgraPktType = IntraCgraPktType
        self.CgraPayloadType = CgraPayloadType
        self.TileInType = TileInType
        self.FuOutType = FuOutType
        self.CMD_CONFIG_ = CMD_CONFIG_input
        self.FuInType = FuInType
        self.ii = ii
        self.loop_times = loop_times
        self.CMD_CONST_ = CMD_CONST_input
        self.CMD_CONFIG_COUNT_PER_ITER_ = CMD_CONFIG_COUNT_PER_ITER_input
        self.CMD_CONFIG_TOTAL_CTRL_COUNT_ = CMD_CONFIG_TOTAL_CTRL_COUNT_input
        self.CMD_CONFIG_PROLOGUE_FU_ = CMD_CONFIG_PROLOGUE_FU_input
        self.CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_ = CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input
        self.CMD_CONFIG_PROLOGUE_FU_CROSSBAR_ = CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input
        self.CMD_LAUNCH_ = CMD_LAUNCH_input
        self.DataType = DataType
        self.B1Type = B1Type
        self.B2Type = B2Type
        self.RegIdxType = RegIdxType
        self.CtrlAddrType = CtrlAddrType
        self.DataAddrType = DataAddrType
        self.num_tile_inports = num_tile_inports
        self.num_tile_outports = num_tile_outports
        self.num_fu_inports = num_fu_inports
    
    def makeVectorCGRAPkts(self):
        
        pkts = {}
        cores = self.yaml_struct['array_config']['cores']
        
        
        for core in cores:
            x, y = core['column'], core['row']
            entry = core['entries'][0]
            instructions = entry['instructions']
            id_ = core['core_id']
            
            tile_signals = TileSignals(
                CtrlType = self.CtrlType,
                IntraCgraPktType = self.IntraCgraPktType,
                CgraPayloadType = self.CgraPayloadType,
                TileInType = self.TileInType,
                FuOutType = self.FuOutType,
                CMD_CONFIG_input = self.CMD_CONFIG_,
                FuInType = self.FuInType,
                id_ = id_,
                loop_times = self.loop_times, 
                ii = self.ii, 
                instructions = instructions,
                CMD_CONST_input = self.CMD_CONST_,
                CMD_CONFIG_COUNT_PER_ITER_input = self.CMD_CONFIG_COUNT_PER_ITER_,
                CMD_CONFIG_TOTAL_CTRL_COUNT_input = self.CMD_CONFIG_TOTAL_CTRL_COUNT_,
                CMD_CONFIG_PROLOGUE_FU_input = self.CMD_CONFIG_PROLOGUE_FU_,
                CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input = self.CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_,
                CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input = self.CMD_CONFIG_PROLOGUE_FU_CROSSBAR_,
                CMD_LAUNCH_input = self.CMD_LAUNCH_,
                DataType = self.DataType,
                B1Type = self.B1Type,
                B2Type = self.B2Type,
                RegIdxType = self.RegIdxType,
                CtrlAddrType = self.CtrlAddrType,
                DataAddrType = self.DataAddrType,
                num_tile_inports = self.num_tile_inports,
                num_tile_outports = self.num_tile_outports,
                num_fu_inports = self.num_fu_inports,
                )
            tile_signals = tile_signals.makeTileSignals()
            pkts[(x, y)] = tile_signals
            
        return pkts
    
from validation.test.dummy import *
    
if __name__ == "__main__":
    print("Test the Basic Functionality of the ScriptFactory")

    script_factory = ScriptFactory(
        path = "./validation/test/fir_acceptance_test.yaml",
        CtrlType = CtrlTypeDummy,
        IntraCgraPktType = IntraCgraPktTypeDummy,
        CgraPayloadType = CgraPayloadTypeDummy,
        TileInType = TileInTypeDummy,
        FuOutType = FuOutTypeDummy,
        CMD_CONFIG_input = CMD_CONFIG_Dummy(),
        FuInType = FuInTypeDummy,
        ii = 4,
        loop_times = 2,
        CMD_CONST_input = CMD_CONST_Dummy(),
        CMD_CONFIG_COUNT_PER_ITER_input = CMD_CONFIG_COUNT_PER_ITER_Dummy(),
        CMD_CONFIG_TOTAL_CTRL_COUNT_input = CMD_CONFIG_TOTAL_CTRL_COUNT_Dummy(),
        CMD_CONFIG_PROLOGUE_FU_input = CMD_CONFIG_PROLOGUE_FU_Dummy(),
        CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_input = CMD_CONFIG_PROLOGUE_ROUTING_CROSSBAR_Dummy(),
        CMD_CONFIG_PROLOGUE_FU_CROSSBAR_input = CMD_CONFIG_PROLOGUE_FU_CROSSBAR_Dummy(),
        CMD_LAUNCH_input = CMD_LAUNCH_Dummy(),
        DataType = DataTypeDummy,
        B1Type = B1TypeDummy,
        B2Type = B2TypeDummy,
        RegIdxType = RegIdxTypeDummy,
        CtrlAddrType = CtrlAddrTypeDummy,
        DataAddrType = DataAddrTypeDummy,
    )
    
    pkts = script_factory.makeVectorCGRAPkts()
    for x, y in pkts:
        print(f"Tile ({x}, {y}):")
        for pkt in pkts[(x, y)]:
            print(pkt)
            print("--------------------------------")
    
