//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    !! THIS VERSION OF GENESIS2 IS NOT FOR ANY COMMERCIAL USE !!
//     FOR COMMERCIAL LICENSE CONTACT SHACHAM@ALUMNI.STANFORD.EDU
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11904 $ --- $Date: 2013/08/03 $   |
//	-----------------------------------------------
//	
//
//  Source file: /nobackup-02/ajokai/eee498/apr/FPmult_plain_mode_noMode_16b_3EffSc_950ps/rtl/FPmult_plain.vp
//  Source template: FPmult_plain
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
// Parameter BW 	= 16
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------





// BW (_GENESIS2_INHERITANCE_PRIORITY_) = 16
//



// DPDA_ 
module FPmult_plain
(
   input logic clk,
   input logic rst,
   //Inputs   
   input logic [15:0] rhs_0,
   input logic [15:0] rhs_1,
   //Outputs   
   output logic [15:0] lhs_0
);
  
  logic a_s;
  logic b_s;
  logic unsigned [4:0] a_e;
  logic unsigned [4:0] b_e;
  logic unsigned [9:0] a_m;
  logic unsigned [9:0] b_m;

  assign a_s = rhs_0[15];
  assign b_s = rhs_1[15];
  assign a_e = rhs_0[14:10];
  assign b_e = rhs_1[14:10];
  assign a_m = rhs_0[9:0];
  assign b_m = rhs_1[9:0];


  logic unsigned [21:0] mantissa_mult;
  //assign mantissa_mult = {1'b1, a_m} * {1'b1, b_m};


  logic [23:0] mul1;
  logic [23:0] mul2;

  logic tc;
  assign tc = 1'b0;

  
  DW02_multp #(11, 11, 24)
          U1 ( 
	     .a({1'b1, a_m}),
	     .b({1'b1, b_m}),
	     .tc(tc),
             .out0(mul1),
	     .out1(mul2)
	     );

  assign mantissa_mult = mul1 + mul2;

  logic unsigned [6:0] potential_exp;
  assign potential_exp = a_e + b_e - 4'd15 + mantissa_mult[21];

 
  assign lhs_0[15] = a_s ^ b_s;

  always_comb
    unique case (1'b1)
      ((~|potential_exp) | potential_exp[6]): // 00..00 or 1??..??
      begin
        lhs_0[14:10] = 5'b01;
        lhs_0[9:0] = 10'b0;
      end
      (((&potential_exp[4:0]) | potential_exp[5]) & ~potential_exp[6]): // 0?11..11 or 01??..??
      begin
        lhs_0[14:10] = {{4{1'b1}}, 1'b0};
        lhs_0[9:0] = {10{1'b1}};
      end
      default:
      begin
        lhs_0[14:10] = potential_exp[4:0];
        lhs_0[9:0] = mantissa_mult[21] ?
                                  mantissa_mult[20:11] :
                                  mantissa_mult[19:10];
      end
    endcase

  /*assign lhs_0[9:0] = mantissa_mult[21] ?
                                  mantissa_mult[20:11] :
                                  mantissa_mult[19:10];
   */
endmodule

