name: Auto PR from Issue (OpenAI)
on:
  workflow_dispatch:
  issues:
    types: [labeled]

jobs:
  create_auto_pr:
    if: github.event.label.name == 'autopr-openai'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git identity for Actions
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install --upgrade pip && pip install openai pyyaml

      - name: Debug dump event (for troubleshooting)
        run: |
          echo "GITHUB_EVENT_PATH=$GITHUB_EVENT_PATH"
          if [ -f "$GITHUB_EVENT_PATH" ]; then
            echo "----- EVENT JSON -----"
            cat "$GITHUB_EVENT_PATH"
            echo "----------------------"
          else
            echo "No event file found"
          fi

      - name: Generate patch using OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.CODEX_API_KEY }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: python .github/scripts/issue_to_pr_openai.py "${{ github.event.issue.number }}" "${{ github.repository }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "auto/issue-${{ github.event.issue.number }}"
          title: "Auto PR for #${{ github.event.issue.number }}"
          commit-message: "Auto changes for issue #${{ github.event.issue.number }}"
          body: "PR automatically generated by OpenAI for issue #${{ github.event.issue.number }}"

