name: Auto PR from Issue (Gemini)

on:
  workflow_dispatch:
  issues:
    types: [labeled]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  create_auto_pr:
    # Run for manual dispatch, or when an issue labeled autopr-gemini, or when a comment starts with /autopr-gemini
    if: ${{ github.event_name == 'workflow_dispatch' ||
            (github.event_name == 'issues' &&
             github.event.label.name == 'autopr-gemini' &&
             github.event.issue.pull_request == null) ||
            (github.event_name == 'issue_comment' &&
             startsWith(github.event.comment.body, '/autopr-gemini')) }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Set up Node (for Gemini CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Gemini CLI
        run: |
          npm install -g @google/gemini-cli@latest
          echo "Gemini CLI version:"
          gemini --version || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Build prompt file (single-line safe)
        env:
          ISSUE_TITLE: ${{ github.event.issue.title || github.event.pull_request.title || '' }}
          ISSUE_BODY: ${{ github.event.issue.body || github.event.comment.body || github.event.pull_request.body || '' }}
        run: |
          PROMPT="You are an assistant that converts a GitHub issue or PR/comment into a set of concrete code changes. Return ONLY a JSON object with schema: {\"files\":[{\"path\":\"relative/path/to/file\",\"content\":\"full file contents\"}],\"commit_message\":\"A concise commit message\"}. Constraints: valid JSON only; if no code changes needed, return {\"files\":[],\"commit_message\":\"no changes needed\"}; only modify source/docs/tests (not .github/workflows); keep edits minimal. Issue title: $ISSUE_TITLE  Issue/Comment body: $ISSUE_BODY"
          echo "$PROMPT" > /tmp/gemini_prompt.txt
          echo "Prompt written to /tmp/gemini_prompt.txt ($(wc -c < /tmp/gemini_prompt.txt) bytes)"
          head -c 400 /tmp/gemini_prompt.txt || true

      - name: Run Gemini CLI and save output
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          set -x
          if command -v gemini >/dev/null 2>&1; then
            gemini chat --model="gemini-1.0" --api-key="${GEMINI_API_KEY}" --prompt-file=/tmp/gemini_prompt.txt > model_output.txt 2>&1 || true
          else
            npx @google/gemini-cli chat --model="gemini-1.0" --api-key="${GEMINI_API_KEY}" --prompt-file=/tmp/gemini_prompt.txt > model_output.txt 2>&1 || true
          fi
          echo "model_output.txt size:"
          wc -c model_output.txt || true

      - name: Debug: show model output head
        if: always()
        run: |
          echo "---- model_output.txt head ----"
          head -n 200 model_output.txt || true
          echo "---- end ----"

      - name: Apply model output with script
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: |
          python .github/scripts/issue_to_pr_gemini.py "${{ github.event.issue.number }}" "${{ github.repository }}" --from-file model_output.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "auto/issue-${{ github.event.issue.number }}"
          title: "Auto PR for #${{ github.event.issue.number }}"
          commit-message: "Auto changes for issue #${{ github.event.issue.number }}"
          body: "PR automatically generated by Gemini (please review)."

